var isIE=!1,url_match=/https?:\/\/([-\w\.]+)+(:\d+)?(\/([\w/_\.]*(\?\S+)?)?)?/;function findMousePos(a){var c=0,b=0,a=a?a:window.event;if(isIE)c=event.clientX+document.body.scrollLeft,b=event.clientY+document.body.scrollTop;else if(a!=void 0)c=a.pageX,b=a.pageY;c<0&&(c=0);b<0&&(b=0);return[c,b]}function findPos(a){var c=etop=0;if(a.offsetParent){do c+=a.offsetLeft,etop+=a.offsetTop;while(a=a.offsetParent);return[c,etop]}}function findElemPos(a){return findPos(a)}
function scrollToElem(a){a=findPos(a);window.scrollTo(a[0],a[1])}function _removeDupStyle(a,c){for(var b=null,b=typeof a.style.cssText=="string"?a.style.cssText.split(";"):a.getAttribute("style").split(";"),d="",e=b.length-1;e>=0;e--){var f=b[e].split(":");c.indexOf(f[0]+":")==-1&&(d+=b[e]+";")}return d}function setStyle(a,c){if(!(a==null||c==null)){var b=_removeDupStyle(a,c);if(typeof a.style.cssText=="string")a.style.cssText=b+c;a.setAttribute("style",b+c)}}
function getStyleProperty(a,c){if(a==null||c==null)return"";for(var b=null,b=typeof a.style.cssText=="string"?a.style.cssText.split(";"):a.getAttribute("style").split(";"),d=b.length-1;d>=0;d--){var e=b[d].split(":");if(c==e[0])return e[1].replace(/^\s+|\s+$/,"")}return""}function addClass(a,c){if(a!=null){var b=a.getAttribute("class");b!=null&&b.length>0?b+=" ":b="";b+=c;a.setAttribute("class",b)}}
function removeClass(a,c){if(a!=null){var b=a.getAttribute("class");if(!(b==null||b.length<=0)){var d=eval("/\\s*"+c+"/"),b=b.replace(d,"");a.setAttribute("class",b)}}}var OKDListeners=null;function fireOnKeyDown(a){for(var c=0;c<OKDListeners.length;c++)OKDListeners[c](a)}function SetupOnKeyDown(){OKDListeners==null&&(OKDListeners=[]);document.onkeydown!=null&&OKDListeners.push(document.onkeydown);document.onkeydown=fireOnKeyDown;document.layers&&document.captureEvents(Event.KEYDOWN)}
function AddOKDListener(a){OKDListeners==null&&SetupOnKeyDown();OKDListeners.push(a);return OKDListeners.length-1}function RemoveOKDListener(a){a=OKDListeners.indexOf(a);if(!(a<0)){for(var c=[],b=OKDListeners.length-1;b>=0;b--)b!=a&&c.unshift(OKDListeners[b]);OKDListeners=c}}Array.prototype.contains=function(a){for(var c=this.length;c--;)if(this[c]!=null){var b=this[c];if(b.equals!=void 0&&b.equals(a))return!0;if(b===a)return!0}return!1};
Array.prototype.indexOf=function(a){for(var c=this.length;c--;){var b=this[c];if(b.equals!=void 0&&b.equals(a))return c;if(b===a)return c}return-1};Object.prototype.toString=function(){var a="{",c=!0;for(p in this){c?c=!1:a+=",";a+="'"+p+"': ";var b=this[p];if(b instanceof Array){a+="[";for(var d=0;d<b.length;d++)d!=0&&(a+=","),a+="'"+b[d]+"'";a+="]"}else a+="'"+b+"'"}a+="}";return a};
var weekdays_short=["Sun","Mon","Tue","Wed","Thu","Fri","Sat"],months_short=["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];function sameDay(a,c){return a.getFullYear()!=c.getFullYear()?!1:a.getMonth()!=c.getMonth()?!1:a.getDate()!=c.getDate()?!1:!0}function sameWeek(a,c){if(a.getFullYear()!=c.getFullYear())return!1;if(a.getMonth()!=c.getMonth())return!1;var b=a.getDate()-a.getDay(),d=b+6;return c.getDate()<b||c.getDate()>d?!1:!0}
function getVagueTime(a){var c=new Date,a=new Date(a),b="";c.getFullYear()!=a.getFullYear()?b=a.getMonth()+"/"+a.getDate()+"/"+a.getFullYear()+" ":sameDay(c,a)||(b=c.getDate()-1==a.getDate()?"Yesterday ":c.getDate()-a.getDate()<3?"A couple of days ago ":sameWeek(c,a)?weekdays_short[a.getDay()]+" ":months_short[a.getMonth()]+" "+a.getDate()+" ");sameDay(c,a)?(b=c.getHours()-a.getHours(),b=a.getHours()>c.getHours()?"From the mysterious future!":b<1?"A few minutes ago":b>=1&&b<2?"About an hour ago":
b>=2&&b<4?"A couple of hours ago":b>=4&&b<=6?"A few hours ago":a.getHours()<11?"This morning":a.getHours()>11&&a.getHours()<17?"This afternoon":"Earlier this evening"):c.getDate()-1==a.getDate()?b+=a.getHours()<11?"morning":a.getHours()>11&&a.getHours()<17?"afternoon":"evening":c.getDate()-a.getDate()>3&&(b+=a.getHours()%12+":"+a.getMinutes(),b+=a.getHours()>11?"pm":"am");return b}function getRandom(a){return Math.floor(Math.random()*a)}
function textToDOM(a){if(a==null)return null;if(a.indexOf(">")==-1&&a.indexOf("<")==-1)return document.createTextNode(a);for(var c=[];a.length>0;){var b=null;if(a.charAt(0)!="<")b=a.substring(0,a.indexOf("<")),a=a.substring(a.indexOf("<")),c.push(document.createTextNode(b));else{var b=a.substring(a.indexOf("<")+1,a.indexOf(">")),d=document.createElement(b),e=a.indexOf("/>"),f=a.indexOf("</"+b+">");if(e<0||e>=f){e=f;f=a.substring(a.indexOf(">")+1,e);if(f.indexOf("<")==-1)d.appendChild(document.createTextNode(f));
else for(var f=textToDOM(f),g=0,i=f.length;g<i;g++){var h=f[g];h!=null&&d.appendChild(h)}a=a.substring(b.length+e+3)}else a=a.substring(b.length+2);c.push(d)}}return c}function setTitle(a){var c=document.getElementsByTagName("title");c.length>0?c.innerHTML=a:(c=document.createElement("title"),c.appendChild(document.createTextNode(a)),document.head.appendChild(c))}
function getDocHeight(){return Math.max(Math.max(document.body.scrollHeight,document.documentElement.scrollHeight),Math.max(document.body.offsetHeight,document.documentElement.offsetHeight),Math.max(document.body.clientHeight,document.documentElement.clientHeight))}function HG_loadOnCondition(a,c,b){c!=null&&(eval(a)?c():setTimeout(function(){HG_loadOnCondition(a,c,b)},b))};
