var LibSlideshow_Active=[];function LibSlideshow(a){this._ThumbnailsLayer=this._ImgLayer=this._MainLayer=null;this._isListening=!1;this._previousListener=null;this.Pictures=a;this.CurrentPicture=-1;a!=null&&this.LoadLarge()}LibSlideshow_KeyboardHandler=function(a){for(var a=a?a:window.event?window.event:null,b=LibSlideshow_Active.length-1;b>=0;b--){var c=LibSlideshow_Active[b];c._isListening&&c._fireKeyboardEvent(a)}};
LibSlideshow.prototype._fireKeyboardEvent=function(a){if(a)switch(a.charChode?a.charCode:a.keyCode?a.keyCode:a.which?a.which:0){case 72:this.Previous();break;case 76:this.Next();break;case 27:this.Exit()}};
LibSlideshow.prototype.ViewPicture=function(a){if(this._ImgLayer!=null){var b="";if(this._ThumbnailsLayer!=null){var c=this._ThumbnailsLayer.getElementsByTagName("img");if(this.CurrentPicture>=0){var d=c[this.CurrentPicture],b=d.getAttribute("class");b!=null&&b.length>0&&d.setAttribute("class",b.replace(/ current/,""))}}this._ImgLayer.setAttribute("src",this.Pictures[a]);this.CurrentPicture=a;this._ThumbnailsLayer!=null&&(a=c[this.CurrentPicture],b=a.getAttribute("class"),b==null&&(b=""),a.setAttribute("class",
b+" current"))}};LibSlideshow.prototype._slidePicture=function(a,b){if(a!=null){var c=(eval(a.CurrentPicture)+eval(b))%a.Pictures.length;c<0&&(c=a.Pictures.length-1);return a.ViewPicture(c)}};LibSlideshow.prototype.Next=function(a){if(!(a<0||a>LibSlideshow_Active.length))return a=LibSlideshow_Active[a],a==null||a.Pictures.length<=1?void 0:a._slidePicture(a,1)};
LibSlideshow.prototype.Previous=function(a){if(!(a<0||a>LibSlideshow_Active.length))return a=LibSlideshow_Active[a],a==null||a.Pictures.length<=1?void 0:a._slidePicture(a,-1)};LibSlideshow.prototype.Next=function(){return this._slidePicture(this,1)};LibSlideshow.prototype.Previous=function(){return this._slidePicture(this,-1)};
LibSlideshow.prototype.Exit=function(){if(this._previoustListener)document.onkeydown=this._previoustListener;this._MainLayer.parentNode.removeChild(this._MainLayer);for(var a=[],b=LibSlideshow_Active.length-1;b>=0;b--)LibSlideshow_Active[b]!=this&&a.unshift(LibSlideshow_Active[b]);LibSlideshow_Active=a};
LibSlideshow.prototype.LoadLarge=function(){LibSlideshow_Active.push(this);var a=LibSlideshow_Active.length-1,b=document.createElement("div");b.setAttribute("class","LibSlideshow");b.setAttribute("LibSlideshow_idx",a);var c=document.createElement("div");c.setAttribute("class","background");b.appendChild(c);var d=document.createElement("div"),c=document.createElement("img");d.appendChild(c);b.appendChild(d);d=null;if(this.Pictures.length>1){document.createElement("span").setAttribute("class","LibSlideshow_Close");
document.createElement("span").setAttribute("class","LibSlideshow_Previous");document.createElement("span").setAttribute("class","LibSlideshow_Next");for(var d=document.createElement("div"),e=this.Pictures.length-1;e>=0;e--){var f=document.createElement("img");f.setAttribute("src",this.Pictures[e]);f.setAttribute("onclick","LibSlideshow_Active["+a+"].ViewPicture("+e+");");d.insertBefore(f,d.firstChild)}b.appendChild(d)}document.body.appendChild(b);this._MainLayer=b;this._ImgLayer=c;this._ThumbnailsLayer=
d;if(document.onkeydown!=null)this._previoustListener=document.onkeydown;document.onkeydown=LibSlideshow_KeyboardHandler;this._isListening=!0;this.Next()};
