var twitterJSON="http://api.twitter.com/1/statuses/user_timeline/hokiegeek.json?count=1",nav_desc_lyr=null,tweet_msg_lyr=null,TWEET_UPDATE_INTERVAL=5E4;
function updateTwitter(d){var f=null,b="\u00a0";if(d==null)f="No tweets!";else{if(eval(d)==null||eval(d)[0]==null)return;var b=eval(d)[0],d=b.text,c=d.match(/(https?:\/\/|[@#])\S+/g),f=document.createElement("span");if(c!=null&&c.length>0){var a=0,g=0;for(i in c)if(!(i=="contains"||i=="indexOf"||i=="shuffle")){var e=c[i],a=d.indexOf(e),h=d.substring(g,a),g=a+e.length;h.length>0&&f.appendChild(document.createTextNode(h));var a=document.createElement("a"),j=h="",k=e.substring(1);switch(e.charAt(0)){case "@":h=
"http://twitter.com/"+k;j="View "+k+"'s twitter stream";break;case "#":h="http://twitter.com/search?q=%23"+k;j="Search twitter for how '"+k+"' is trending";break;default:h=e}a.setAttribute("href",h);a.setAttribute("title",j);a.appendChild(document.createTextNode(e));f.appendChild(a)}}else f.appendChild(document.createTextNode(d));d=b.created_at;b="shhhh....";d!=null&&(b=getVagueTime(d))}tweet_msg_lyr==null&&(tweet_msg_lyr=document.getElementById("tweet").getElementsByTagName("div")[0]);if(f!=null&&
(tweet_msg_lyr.removeChild(tweet_msg_lyr.firstChild),tweet_msg_lyr.insertBefore(f,tweet_msg_lyr.firstChild),b!=null))tweet_msg_lyr.firstChild.nextSibling.innerHTML=b}function requestTweet(){(new libHTTPRequest).getData(twitterJSON,null,updateTwitter,!0)}function showSubDesc(d){setStyle(nav_desc_lyr,"visibility: visible;");nav_desc_lyr.innerHTML=hg_subdomains[d][1]}
function setupSubdomainDesc(){for(var d=document.getElementById(hg_nav_subs_id).getElementsByTagName("a"),f=d.length-1;f>=0;f--)d[f].setAttribute("onmouseover","showSubDesc("+f+")"),d[f].setAttribute("onmouseout","setStyle(nav_desc_lyr, 'visibility: hidden;')")}function loadingMessage(){}var featuresMgr=null,readingTabs=null;
function createTableFromObject(d,f){for(var b=document.createElement("table"),c=null,a=null,g=0;g<f.length;g++){p=f[g];var e=p.charAt(0).toUpperCase()+p.substr(1),h="n/a";d[p]!=null&&(h=d[p].getName!=void 0?d[p].getName():d[p]);c=document.createElement("tr");a=document.createElement("td");a.appendChild(document.createTextNode(e));c.appendChild(a);a=document.createElement("td");a.appendChild(document.createTextNode(h));c.appendChild(a);b.appendChild(c)}return b}
function setupFeatures(d){featuresMgr==null&&(featuresMgr=new HG_FeatureManager,featuresMgr.create(d));featuresMgr.addFeature(new HG_FeatureView(new HG_Feature("Baby Butt Smooth",function(){this.data=ShavingJournalEntries[0];this.data_updated=!0},function(){getShavingData(null);return"(ShavingJournalEntries != undefined && ShavingJournalEntries.length > 0)"},30),function(f){if(f==null)return!1;if(!this.data.data_updated||this.data.data==null)return!1;var b=this.data.data;if(b==null)return console.log("ERROR: Could not find shaving data!"),
!1;else console.log("Found shaving data: ",b);document.createElement("div").setAttribute("class","hg_feature_content_pic");var c=document.createElement("img"),a=b.Razor.Pictures[0];a.getURL!=void 0&&(a=a.getURL(200));c.setAttribute("src",a);f.appendChild(c);c=document.createElement("div");a=[];a.push("Razor");a.push("Brush");b.Strop!=null?a.push("Strop"):a.push("Blade");b.Cream!=null?a.push("Cream"):a.push("Soap");for(var a=createTableFromObject(b,a),d=document.createElement("div"),e=0;e<grade_scale.length;e++){var h=
document.createElement("img"),j="shaving/img/shave_grade_"+grade_scale[e].toLowerCase();j+=grade_scale[e]!=b.Grade?"_dark":"";j+=".png";h.setAttribute("src",j);h.setAttribute("title",grade_scale[e]);d.appendChild(h)}tr=document.createElement("tr");cell=document.createElement("td");tr.appendChild(cell);cell=document.createElement("td");cell.appendChild(d);tr.appendChild(cell);a.appendChild(tr);c.appendChild(a);f.appendChild(c);return!0}));featuresMgr.addFeature(new HG_FeatureView(new HG_Feature("Give us a Cuppa, Govna",
function(){this.data=TeaJournalEntries[0];this.data_updated=!0},function(){getTeaData(null);return"(TeaJournalEntries != undefined && TeaJournalEntries.length > 0)"},30),function(d){if(d==null)return!1;var b=this.data.data,c=document.createElement("img");c.setAttribute("class","hg_feature_content_pic");c.setAttribute("src",b.Tea.Pictures[0].getURL(200));d.appendChild(c);document.createElement("div");document.createElement("table");c=document.createElement("div");c.setAttribute("id","latest_cuppa_tea_name");
c.appendChild(document.createTextNode(b.Tea.getName()));b.Tea.Type!="Blend"&&c.appendChild(document.createTextNode(" ("+b.Tea.Type+")"));var a=b.Fixins;if(a!=null){var g=document.createElement("div");g.setAttribute("id","latest_cuppa_tea_fixins");g.innerHTML="with ";for(var e=a.length-1;e>=0;e--)e==0?g.innerHTML+=" and ":e!=a.length-1&&(g.innerHTML+=", "),g.innerHTML+=a[e].toLowerCase();c.appendChild(g)}d.appendChild(c);if(b.EntryDate!=null||b.SteepTime!=null||b.Temperature!=null||b.SteepingVessel!=
null)c=document.createElement("div"),c.setAttribute("id","latest_cuppa_steeping_details"),c.innerHTML="Steeped ",c.innerHTML+=getVagueTime(b.Date).toLowerCase()+" ",b.SteepTime!=null&&(c.innerHTML+="for <i>"+formatSteepTime(b.SteepTime)+"</i> "),b.Temperature!=null&&(c.innerHTML+="<br />at <i>"+b.Temperature+"&deg;F</i> "),b.SteepingVessel!=null&&(c.innerHTML+="using the "+b.SteepingVessel.toLowerCase()),d.appendChild(c);a=document.createElement("div");a.setAttribute("id","latest_cuppa_rating");for(g=
0;g<4;g++)c=document.createElement("img"),e="tea/img/tea_cup",g>b.Rating-1&&(e+="_greyed"),e+=".png",c.setAttribute("src",e),c.setAttribute("title",b.Rating+"/4 steaming tea cups"),a.appendChild(c);d.appendChild(a);return!0}))};
