var libHTTPRequest_Requests=[],libHTTPRequest_Constants={MSXML_VERS:["MSXML2.XMLHttp.6.0","MSXML2.XMLHttp.5.0","MSXML2.XMLHttp.4.0","MSXML2.XMLHttp.3.0","MSXML2.XMLHttp","Microsoft.XMLHttp"],useActiveX:typeof ActiveXObject!="undefined",useDom:document.implementation&&document.implementation.createDocument,useXmlHttp:typeof XMLHttpRequest!="undefined"};
function libHTTPRequest_DataManager(){this.Scripts=["http://"+window.location.hostname+"/sss/XDRequest.php"];this.StoreLocation="http://"+window.location.hostname+"/sss/gen"}function libHTTPRequest(){this.Request=this.Callback=this.Options=this.URL=null;this.Store=!1;this.StoreFileName="libHTTPRequest";this.DataManager=new libHTTPRequest_DataManager;this.DataScript=null;this._load()}
libHTTPRequest.prototype._load=function(){for(var a=new libHTTPRequest_DataManager,b=0;b<a.Scripts.length;b++)if(this.ping(a.Scripts[b])){this.DataScript=a.Scripts[b];break}};
libHTTPRequest.prototype._XmlHttpReq=function(){if(libHTTPRequest_Constants.useXmlHttp)return new XMLHttpRequest;else if(libHTTPRequest_Constants.useActiveX)for(var a=0;a<libHTTPRequest_Constants.MSXML_VERS.length;a++)try{return new ActiveXObject(libHTTPRequest_Constants.MSXML_VERS[a])}catch(b){}throw Error("XMLHttp object could not be created.");};
libHTTPRequest._onreadystatechange=function(a){var b=libHTTPRequest_Requests[a],c=b.Request,d=b.Callback,b=b.Store;if(c!=null&&c.readyState=="4")switch(c.status){case 200:case 201:case 202:case 203:case 204:case 205:case 206:case 207:var e=null,e=c.responseXML&&c.responseXML.length>0?c.responseXML:c.responseText;e!=null&&d!=null?d(e):b&&libHTTPRequest._loadFromBackup(a);break;default:b&&libHTTPRequest._loadFromBackup(a)}};
libHTTPRequest._loadFromBackup=function(a){var b=libHTTPRequest_Requests[a],c=new libHTTPRequest_DataManager;this.StoreLocation="http://dl.dropbox.com/u/6524/hokiegeek.net/sss/gen";a=b.getXmlRequest("GET",c.StoreLocation+"/"+b.StoreFileName+".json",a);b.Request=a;a.send(null)};libHTTPRequest.prototype.ping=function(a){var b=this._XmlHttpReq(),c=!1;b.open("GET",a,!1);try{b.send(null),b!=null&&b.readyState=="4"&&b.status>=200&&b.status<=207&&(c=!0)}catch(d){}return c};
libHTTPRequest.prototype.getXmlRequest=function(a,b,c){var d=this._XmlHttpReq();d.onreadystatechange=function(){libHTTPRequest._onreadystatechange(c)};d.open(a,b,!0);return d};
libHTTPRequest.prototype.getData=function(a,b,c,d){if(a!=void 0){this.URL=a;this.Options=b;this.Callback=c;if(this.Store=d)c=a,a.indexOf("?")!=-1&&(c=a.substring(0,a.indexOf("?"))),c=c.replace(/https?:\/\//g,"").replace(/(\/|\.|\-|=|&)/g,"_"),this.StoreFileName+="__"+c,b+="&store="+this.StoreFileName;libHTTPRequest_Requests.push(this);this.Request=a=this.getXmlRequest("GET",this.DataScript+"?u="+a+"&"+b,libHTTPRequest_Requests.length-1);a.send(null)}};
libHTTPRequest.prototype.sendData=function(a,b){this.URL=a;this.Options=b;for(var c="",d=0;d<b.length;d++)d>0&&(c+="&"),c+=b[d];libHTTPRequest_Requests.push(this);d=this.getXmlRequest("POST",this.DataScript+"?u="+a,libHTTPRequest_Requests.length-1);d.setRequestHeader("Content-type","application/x-www-form-urlencoded");this.Request=d;d.send(c)};
