function PicasaWeb_Pic(b){this.data=b;this.caption=this.url=this.name=this.id=null;this.height=this.width=0;this.loaded=!1;this._load()}PicasaWeb_Pic.prototype.isLoaded=function(){return this.loaded};PicasaWeb_Pic.prototype.getURL=function(b){var a=this.url;b!=void 0&&b!=null&&(a+="/s"+b);a+="/"+this.name;return a};
PicasaWeb_Pic.prototype._load=function(){if(!(this.data==null&&this.data==void 0)){for(var b=this.data.length-1;b>=0;b--){var a=this.data[b];if(a!=null)if(a.title)this.name=a.title.$;else if(a.id){if(a=a.id.$,a!=null&&a!=void 0)this.id=a.slice(a.lastIndexOf("/")+1)}else if(a.content&&a.content!=null)a=a.content["@"].src,this.url=a.substr(0,a.lastIndexOf("/"))}this.loaded=!0}};
function PicasaWeb_Album(b,a){this.ALBUM_PICS_URL="https://picasaweb.google.com/data/feed/api/user/"+b+"/albumid";this.user=b;this.data=a;this.name=null;this.id=-1;this.Pics=this.updated=this.summary=this.url=null;this._load()}PicasaWeb_Album.prototype.isLoaded=function(){return this.isLoaded(null)};PicasaWeb_Album.prototype.isLoaded=function(b){if(this.Pics==null)return!1;for(var a=this.Pics.length-1;a>=0;a--)if(!(b!=void 0&&b!=null&&this.Pics[a].name!=b)&&!this.Pics[a].isLoaded())return!1;return!0};
PicasaWeb_Album.prototype.Size=function(){return this.Pics==null?0:this.Pics.length};PicasaWeb_Album.prototype.getPicture=function(b){for(var a=this.Pics.length-1;a>=0;a--)if(this.Pics[a].name==b)return this.Pics[a];return null};PicasaWeb_Album.prototype._retrievePics=function(b){if(this.Pics==null||this.Pics==void 0)this.Pics=[];if(b!=null&&b.length>0)for(var a=b.length-1;a>=0;a--)b[a]!=null&&this.Pics.push(new PicasaWeb_Pic(b[a]))};
PicasaWeb_Album.prototype._load=function(){for(var b=this.data.length-1;b>=0;b--){var a=this.data[b];if(a!=null)if(a.title)this.name=a.title.$;else if(a.id)a=a.id.$,this.id=a.slice(a.lastIndexOf("/")+1),this.url=this.ALBUM_PICS_URL+"/"+this.id;else if(a.summary)this.summary=a.summary.$}if(!(this.name!="HG_Shaving"&&this.name!="HG_Tea"&&this.name!="Our First House")&&this.id!=null){PicasaWebObjects_retrieving.push(this);var c=PicasaWebObjects_retrieving.length-1;getGoogleData(new PicasaWebRetrieval(this.url,
function(a){var b=PicasaWebObjects_retrieving[c];(b!=null||b!=void 0)&&b._retrievePics(a)},null))}};function PicasaWeb(b){this.USER_ALBUMS_URL="https://picasaweb.google.com/data/feed/api/user/"+b+"&access=private";this.user=b;this.Albums=this.cover=null;this._load()}PicasaWeb.prototype.isLoaded=function(){return this.isLoaded(null)};
PicasaWeb.prototype.isLoaded=function(b){if(this.Albums==null)return!1;for(var a=this.Albums.length-1;a>=0;a--)if(!(b!=void 0&&b!=null&&this.Albums[a].name!=b)&&!this.Albums[a].isLoaded())return!1;return!0};PicasaWeb.prototype.getAlbum=function(b){if(this.Albums!=null)for(var a=this.Albums.length-1;a>=0;a--)if(this.Albums[a].name==b)return this.Albums[a];return null};
PicasaWeb.prototype._retrieveAlbums=function(b){if(this.Albums==null||this.Albums==void 0)this.Albums=[];if(b!=null&&b.length>0)for(var a=b.length-1;a>=0;a--)(b[a]!=null||b[a]!=void 0)&&this.Albums.push(new PicasaWeb_Album(this.user,b[a]))};PicasaWeb.prototype._load=function(){PicasaWebObjects_retrieving.push(this);var b=PicasaWebObjects_retrieving.length-1;getGoogleData(new PicasaWebRetrieval(this.USER_ALBUMS_URL,function(a){PicasaWebObjects_retrieving[b]._retrieveAlbums(a)},null))};
var PicasaWebObjects_retrieverCount=-1,PicasaWebObjects_retrieving=[];PicasaWebRetrieval.prototype=new GoogleDataRetrieval;function PicasaWebRetrieval(b,a,c){this.URL=b;this.UserCallback=a;this.UserCallbackArguments=c;this.Service="lh2";this.ArrayPos=-1;this.httpReq=new libHTTPRequest}function PicasaWeb_PicView(b,a){this.pic=b;this.elem=a;this.PIC_CLASSNAME="PicasaWeb_PicView";this.PIC_SIZE=300;this._load()}
PicasaWeb_PicView.prototype._load=function(){if(this.elem!=null){this.elem.innerHTML="";addClass(this.elem,this.PIC_CLASSNAME);var b=document.createElement("img");b.setAttribute("src",this.pic.getURL(this.PIC_SIZE));this.elem.appendChild(b)}};
function PicasaWeb_AlbumView(b,a,c){this.album=b;this.elem=a;this.display_header=c;this.pics_view=this.header_view=null;this.ALBUM_CLASSNAME="PicasaWeb_AlbumView";this.ALBUM_HEADER_CLASSNAME="PicasaWeb_AlbumView_Header";this.ALBUM_PICS_CLASSNAME="PicasaWeb_AlbumView_Pics";this._load()}
PicasaWeb_AlbumView.prototype._load=function(){if(this.elem!=null){this.elem.innerHTML="";addClass(this.elem,this.ALBUM_CLASSNAME);if(this.display_header){this.header_view=document.createElement("div");addClass(this.header_view,this.ALBUM_HEADER_CLASSNAME);var b=document.createElement("span");b.appendChild(document.createTextNode(this.album.name));this.header_view.appendChild(b);this.elem.appendChild(this.header_view)}this.pics_view=document.createElement("div");addClass(this.pics_view,this.ALBUM_PICS_CLASSNAME);
for(b=this.album.Pics.length-1;b>=0;b--){var a=document.createElement("span");new PicasaWeb_PicView(this.album.Pics[b],a);this.pics_view.insertBefore(a,this.pics_view.firstChild)}this.elem.appendChild(this.pics_view)}};function PicasaWeb_View(b,a){this.albums=b;this.elem=a;this.album_views=null;this.ALBUMS_CLASSNAME="PicasaWeb_View"}PicasaWeb_View.prototype._load=function(){this.elem.innerHTML="";addClass(this.elem,this.ALBUMS_CLASSNAME)};var PicasaWeb_PicSelectObjs=[];
function PicasaWeb_PicSelect(b,a,c,d){console.log("PicasaWeb_PicSelect()");b=new PicasaWeb_PicSelect_View(b,a,c);if(b==null)return[];console.log("   creating selection control");b.pos=PicasaWeb_PicSelectObjs.length;PicasaWeb_PicSelectObjs.push(b);b.show_header=!1;b.multiselect=d;b.load();return b}
function PicasaWeb_PicSelect_View(b,a,c){this.album=b;this.elem=a;this.pos=-1;this.thumb_size=50;this.multiselect=this.show_header=!0;this.callback=c;this.Selected=[];this.PICSELECT_CLASSNAME="PicasaWeb_PicSelect";this.PICSELECT_PICS_CLASSNAME="PicasaWeb_PicSelect_Pics";this.PICSELECT_PIC_CLASSNAME="PicasaWeb_PicSelect_Pic";this.PICSELECT_SELECTED_CLASSNAME="PicasaWeb_PicSelect_Pic_Selected";this.PICSELECT_HDR_CLASSNAME="PicasaWeb_PicSelect_Header";this.PICSELECT_BTN_CLASSNAME="PicasaWeb_PicSelect_Button"}
PicasaWeb_PicSelect_View.prototype.select=function(b,a){this.Selected.contains(b)?(this.Selected.splice(this.Selected.indexOf(b),1),removeClass(a,this.PICSELECT_SELECTED_CLASSNAME)):(this.Selected.push(b),addClass(a,this.PICSELECT_SELECTED_CLASSNAME),this.multiselect||this.close())};PicasaWeb_PicSelect_View.prototype.getSelected=function(){for(var b=[],a=0;a<this.Selected.length;a++)b.push(this.album.Pics[this.Selected[a]]);return b};
PicasaWeb_PicSelect_View.prototype.close=function(){if(this.elem!=null)this.elem.innerHTML="";this.callback!=null&&this.callback(this.getSelected())};
PicasaWeb_PicSelect_View.prototype.load=function(){if(this.album==null||this.elem==null)console.log("WTF?",this.album,this.elem);else{var b=document.createElement("div");addClass(b,this.PICSELECT_CLASSNAME);if(this.show_header){var a=document.createElement("div");addClass(a,this.PICSELECT_HDR_CLASSNAME);if(this.multiselect){var c=document.createElement("div");addClass(c,this.PICSELECT_BTN_CLASSNAME);c.setAttribute("onclick","PicasaWeb_PicSelectObjs["+this.pos+"].close()");c.appendChild(document.createTextNode("Done"));
a.appendChild(c)}c=document.createElement("div");c.appendChild(document.createTextNode(this.album.name+" ("+this.album.Pics.length+")"));a.appendChild(c);b.appendChild(a)}a=document.createElement("div");addClass(a,this.PICSELECT_PICS_CLASSNAME);for(var c=this.album.Pics,d=0;d<c.length;d++){var e=document.createElement("img");e.setAttribute("src",c[d].getURL(this.thumb_size));e.setAttribute("onclick","PicasaWeb_PicSelectObjs["+this.pos+"].select("+d+", this)");addClass(e,this.PICSELECT_PIC_CLASSNAME);
a.appendChild(e)}b.appendChild(a);this.elem.appendChild(b)}};
