var tabsObj=null;
function renderShavingJournalEntry(h,b){var a=null,f=null,c=document.createElement("img");b.Tea.Pictures[0]==void 0?c.setAttribute("src","img/tea_cup_greyed.png"):c.setAttribute("src",b.Tea.Pictures[0].getURL(120));a=document.createElement("tr");f=document.createElement("td");f.appendChild(c);a.appendChild(f);f=document.createElement("td");c=document.createElement("div");c.setAttribute("class","tea_journal_entry_name");c.appendChild(document.createTextNode(b.Tea.getName()));c.appendChild(document.createTextNode(" ("+b.Tea.getType()+
")"));var g=b.Fixins;if(g!=null){var d=document.createElement("div");d.setAttribute("class","tea_journal_entry_fixins");d.innerHTML="with ";for(var e=g.length-1;e>=0;e--)e==0?d.innerHTML+=" and ":e!=g.length-1&&(d.innerHTML+=", "),d.innerHTML+=g[e].toLowerCase();c.appendChild(d)}f.appendChild(c);g=document.createElement("div");g.setAttribute("class","tea_journal_entry_rating");for(d=0;d<4;d++)c=document.createElement("img"),e="img/tea_cup",d>b.Rating-1&&(e+="_greyed"),e+=".png",c.setAttribute("src",
e),c.setAttribute("title",b.Rating+"/4 steaming tea cups"),g.appendChild(c);f.appendChild(g);a.appendChild(f);h.appendChild(a);a!=void 0&&delete a;f!=void 0&&delete f;return!0}
function loadTeaJournal(){for(var h=$("<table></table>"),b=0;b<TeaJournalEntries.length;b++){var a=TeaJournalEntries[b];console.log("loadTeaJournal(): ",TeaJournalEntries[b]);h.append($("<tr></tr>").append($("<td></td>").append(HG_formatDate(new Date(a.EntryDate)))).append($("<td></td>").append(a.Tea.getName())))}$("#journal_tab").append(h);displayed_entries=TeaJournalEntries.length;console.log("Done adding journal entries")}
function renderTeaJournalEntry(h){for(var b=$("<table></table>"),a=0;a<TeaJournalEntries.length;a++)h=TeaJournalEntries[a],console.log("loadTeaJournal(): ",TeaJournalEntries[a]),b.append($("<tr></tr>").append($("<td></td>").append(HG_formatDate(new Date(h.EntryDate)))).append($("<td></td>").append(h.Tea.getName())));$("#journal_tab").append(b);displayed_entries=TeaJournalEntries.length;console.log("Done adding journal entries")}
function loadTeaProducts(){for(var h=$("<table></table>"),b=0;b<TeaProductEntries.length;b++){var a=TeaProductEntries[b],f=a.Pictures[0]==void 0?"img/tea_cup_greyed.png":a.Pictures[0].getURL(140),f=$("<img />").attr("src",f),c="";a.PurchasePrice!=null&&(c+="$"+a.PurchasePrice+" ");a.PurchaseLocation!=null&&(c+="from "+a.PurchaseLocation+" ");a.PurchaseDate!=null&&(c+="on "+HG_formatDate(a.PurchaseDate));var g="";a.Size!=void 0&&(g+=a.Size+" ");g+=a.getPackaging();for(var d=0,e=a.getJournalEntries(),
i=0;i<e.length;i++)e[i].Rating>1&&(d+=parseInt(e[i].SteepTime));d>0?(d/=e.length,d=formatSteepTime(d)):d="N/A";e=$("<table></table>").addClass("tea_product_entry_details");a.Type!="Blend"&&e.append($("<tr></tr>").append($("<td></td>").append("Origin")).append($("<td></td>").append(a.getOrigin())).append($("<td></td>").append("Price")).append($("<td></td>").append(c)));e.append($("<tr></tr>").append($("<td></td>").append("Packaging")).append($("<td></td>").append(g)).append($("<td></td>").append("Steep Time")).append($("<td></td>").append(d).attr("title",
"Steep Time: Averaged from best journal entries"))).append($("<tr></tr>").append($("<td></td>").append("Ratings")).append($("<td></td>").append("TODO")));a=$("<table></table>").append($("<tr></tr>").addClass("tea_product_entry_name").append($("<td></td>").append(a.getName()+" ["+a.ID+"]").append($("<span></span>").append(a.Stocked?"":"X")).append($("<div></div>").addClass("tea_product_entry_type").append("&lt;"+a.getType().toLowerCase()+"&gt;")))).append($("<tr></tr>").append($("<td></td>").append(e)));
h.append($("<tr></tr>").addClass("tea_product_entry").append($("<td></td>").addClass("tea_product_entry_pics").append(f)).append($("<td></td>").append(a)))}$("#products_tab").append($("<div></div>").attr("id","products_scroller").append(h))}
function loadExtras(){sortTeaJournal();sortTeaProducts();HG_loadJournalViews([new HG_Journals_View("TeaJournalEntries",null,"journal_tab","renderShavingJournalEntry"),new HG_Journals_View("TeaProductEntries",null,"products_tab",function(){loadTeaProducts(0,"DESC","TYPE",null)})],null)}function HG_Journal_local_init(){getTeaData(loadExtras)};
