var url_journal="https://spreadsheets.google.com/feeds/list/tCDnYTlWeLx4Y8C-7jYtK1g/od6/private/full",url_reviews="https://spreadsheets.google.com/feeds/list/tALoFhT7abBDqZ7s0IHAQpg/od6/private/full",ShavingAlbum=null,ShavingReviewedProducts=[],ShavingJournalEntries=[],ShavingCombos=[],grade_scale=["Meh","CCS","DFS","BBS"],PRODUCT_CATEGORIES=["razor","blade","strop","brush","cream","soap","preshave","aftershave","cologne","other"],PRODUCT_GRADES=[["Weight","Aggresiveness","Balance","Grip","Look",
"Price","Quality"],["Longevity","Sharpness","Price","Quality"],["Draw","Thickness","Ergonomic","Look","Efficacy","Price","Quality"],["Density","Stiffness","Softness","Ergonomic","Latherability","Price","Quality"],["Lather","Scent","Efficacy","Slickness","Price","Quality"],["Lather","Scent","Efficacy","Slickness","Price","Quality"],["Scent","Efficacy","Price","Quality"],["Cooling","Burn","Scent","Efficacy","Price","Quality"],["Scent","Longevity","Price","Quality"],["Efficacy","Price","Look","Quality"]];
function ShavingComboType(c){this.Aftershave=this.PreShave=this.Soap=this.Cream=this.Brush=this.Blade=this.Razor=null;this.Dates=[];this.Grades=[];this.Grade=-1;this._calculateGrade=function(){this.Grade=0;for(var a=[grade_scale.length],b=grade_scale.length-1;b>=0;b--)a[b]=0;for(b=this.Grades.length-1;b>=0;b--)a[grade_scale.indexOf(this.Grades[b])]++;for(b=a.length-1;b>=0;b--)this.Grade+=a[b]*grade_scale.indexOf(grade_scale[b])};this.loadCombo=function(a){this.Razor=a.Razor;this.Blade=a.Blade;this.Brush=
a.Brush;this.Soap=a.Soap;this.Cream=a.Cream;this.Preshave=a.Preshave;this.Aftershave=a.Aftershave;this.Dates.push(a.Date);this.Grades.push(a.Grade);this._calculateGrade()};this.addDate=function(a){this.Dates.push(a)};this.addGrade=function(a){this.Grades.push(a)};this.merge=function(a){this.Dates.push(a.Date);this.Grades.push(a.Grade);this._calculateGrade()};this.equals=function(a){return this.Razor!=a.Razor?!1:this.Blade!=a.Blade?!1:this.Brush!=a.Brush?!1:this.Soap!=a.Soap?!1:this.Cream!=a.Cream?
!1:this.Preshave!=a.Preshave?!1:!0};this.loadCombo(c)}
function ProductType(c){this.PurchaseDate=this.Attributes=this.Scent=this.Color=this.Size=this.Name=this.Vendor=this.Type=this.ID=null;this.inDen=!0;this.Grades=this.Location=this.Price=null;this.Grade=-1;this.ReviewComments=this.ReviewDate=null;this.Pictures=[];this._loadPictures=function(a){if(a!=void 0){this.Pictures=a.split(";");this.Pictures.pop();for(a=this.Pictures.length-1;a>=0;a--)this.Pictures[a]=ShavingAlbum!=null?ShavingAlbum.getPicture(this.Pictures[a]):null,this.Pictures[a]==null&&(this.Pictures[a]=
"img/default.png")}};this._calculateGrade=function(a){if(!(a==null||a.length<=0))if(a=a.split(";"),!(a.length<=0)){for(var b=0,c=a.length-1;c>=0;c--)b+=eval(a[c]);this.Grade=Math.floor(b/a.length)}};this._load=function(a){if(a!=null){this.ID=a.id;this.Type=a.producttype;this.Vendor=a.productvendor;this.Name=a.productname;this.Size=a.size;this.Color=a.color;this.Scent=a.scent;if(a.purchasedate!=null)this.PurchaseDate=new Date(a.purchasedate);this.Price=a.purchaseprice;this.Location=a.purchaselocation;
this.Grades=a.grades;this.ReviewDate=new Date(a.reviewdate);this.ReviewComments=a.comments;if(a.inden!=null)this.inDen=eval(a.inden.toLowerCase());this._loadPictures(a.pictures);this._calculateGrade(this.Grades)}};this.search=function(a){var b=this.Vendor+" "+this.Name;this.Color!=null&&(b+=" "+this.Color);this.Size!=null&&(b+=", "+this.Size);this.Scent!=null&&(b+=" "+this.Scent);return b.search(a)};this.equals=function(a){for(var b in this)if(a[b]==void 0||this[b]!=a[b])return!1;return!0};this.getName=
function(){var a=this.Name;if(this.Vendor!=void 0)a=this.Vendor,this.Scent!=null&&this.Scent.length>0&&(a+=" "+this.Scent),this.Name!=null&&this.Name.length>0&&(a+=" "+this.Name),this.Color!=null&&this.Color.length>0&&(a+=" "+this.Color),this.Size!=null&&this.Size.length>0&&(a+=" ("+this.Size+")");return a};this._load(c)}
function JournalEntryType(c){this.Grade=this.NumPasses=this.AdjustableSetting=this.Aftershave=this.Preshave=this.Cream=this.Soap=this.Brush=this.Blade=this.Strop=this.Razor=this.Date=null;this.Grades={Lather:0,Closeness:0,Nicks:0};this.Notes=null;this._getReview2=function(a,b){if(b==null)return b;for(var c=b.split(" "),e=ShavingReviewedProducts.length-1;e>=0;e--){var d=ShavingReviewedProducts[e];if(d.Type.toLowerCase()==a.toLowerCase()){var f=d.Vendor;d.Scent!=null&&(f+=" "+d.Scent);d.Name!=null&&
d.Name.length>0&&(f+=" "+d.Name);d.Color!=null&&(f+=" "+d.Color);d.Size!=null&&(f+=" "+d.Size);for(var d=!1,g=0;g<c.length;g++){var h=c[g].replace(/(\(|\))/g,"");if(f.indexOf(h)==-1){d=!0;break}}if(!d&&ShavingReviewedProducts[e].Type.toLowerCase()=="soap")return ShavingReviewedProducts[e]}}return b};this._getReview=function(a,b){if(isNaN(b))return this._getReview2(a,b);else{var c=HG_getProductByID(ShavingReviewedProducts,eval(b));if(c!=null)return c}return b};this._load=function(a){if(a!=null)this.Date=
new Date(a.date),this.Razor=this._getReview("Razor",a.razor),this.Strop=this._getReview("Strop",a.strop),this.Blade=this._getReview("Blade",a.blade),this.Brush=this._getReview("Brush",a.brush),a.soap!=null&&a.soap.length>0?this.Soap=this._getReview("Soap",a.soap):this.Cream=this._getReview("Cream",a.cream),this.Preshave=this._getReview("Preshave",a.preshave),this.Aftershave=this._getReview("Aftershave",a.aftershave),this.NumPasses=a.numpasses,this.Notes=a.notes,this.Grades.Lather=a.gradelather,this.Grades.Closeness=
a.gradecloseness,this.Grades.Nicks=a.gradenicks,this._calculateGrade()};this.equals=function(){};this._calculateGrade=function(){var a=0,b=0,c;for(c in this.Grades)b+=eval(this.Grades[c]),a++;this.NumPasses>4&&a++;b=Math.floor(b/a);this.Grade=grade_scale[b]};this._load(c)}function sortJournalEntries(c){(c==void 0||c==null)&&ShavingJournalEntries.sort(function(a,b){return!(a.Date instanceof Date)?1:!(b.Date instanceof Date)?0:a.Date.getTime()-b.Date.getTime()})}
function sortProducts(c){c==void 0||c==null?ShavingReviewedProducts.sort(function(a,b){return a.ReviewDate.getTime()==b.ReviewDate.getTime()?a.Grade-b.Grade:a.ReviewDate.getTime()-b.ReviewDate.getTime()}):ShavingReviewedProducts.sort(function(a,b){return a[c]!=null&&b[c]!=null?a[c]-b[c]:a.ReviewDate.getTime()==b.ReviewDate.getTime()?a.Grade-b.Grade:a.ReviewDate.getTime()-b.ReviewDate.getTime()})}function sortShavingCombos(){ShavingCombos.sort(function(c,a){return c.Grade-a.Grade})}
function createShavingCombos(){for(var c=ShavingJournalEntries.length-1;c>=0;c--){var a=new ShavingComboType(ShavingJournalEntries[c]),b=ShavingCombos.indexOf(a);b!=-1?ShavingCombos[b].merge(ShavingJournalEntries[c]):ShavingCombos.push(a)}}
function getShavingData(c){HG_getJournalData({album_id:"HG_Shaving",album_var:"ShavingAlbum",spreadsheets:[{name:"reviews",entries_var:"ShavingReviewedProducts",entries_type:"ProductType",retrieval_url:url_reviews},{name:"journal",entries_var:"ShavingJournalEntries",entries_type:"JournalEntryType",retrieval_url:url_journal}],loaded_callback:c},HG_Journal_loadingMessage)};
