var journalSorterLyr=null,journalTable=null,filteredTabsHeight=305,PIC_SIZE_FULL=1600,PIC_SIZE_THUMB=300,PIC_SIZE_SOTD=450,displayed_reviews=0;function viewReviewSlideshow(b){if(!(b<0||ShavingReviewedProducts[b].Pictures.length<=0)){for(var b=ShavingReviewedProducts[b],g=[],a=0;a<b.Pictures.length;a++){var e=b.Pictures[a];e.getURL?g.push(e.getURL(PIC_SIZE_FULL)):g.push(e)}new LibSlideshow(g);b!=void 0&&delete b;g!=void 0&&delete g}}
function viewReviewPicture(b,g){var a=document.getElementById("review_pic_"+b),e=document.getElementById("current_pic_"+b),c=ShavingReviewedProducts[b];if(!(a==null||e==null||c.Pictures.length<=1)){var h=e.value;if(h==null||h<0)h=0;h=(eval(h)+eval(g))%c.Pictures.length;h<0&&(h=c.Pictures.length-1);c=c.Pictures[h];c.getURL?a.setAttribute("src",c.getURL(PIC_SIZE_FULL)):a.setAttribute("src",c);e.setAttribute("value",h)}}
function refreshReviews(b){for(var g=document.getElementById("review_tabs"),a=g.getElementsByTagName("div"),e=0;e<a.length;e++)a[e].getAttribute("class").indexOf("tab_content")!=-1&&(height=parseInt(document.documentElement.clientHeight-filteredTabsHeight),setStyle(a[e],"height: "+height+"px !important;"));tabsObj.NestedTabs[1].ReloadTabs();b!=void 0&&b!=null?tabsObj.NestedTabs[1].ToggleTab(b):tabsObj.NestedTabs[1].ToggleTab(0);g!=void 0&&g!=null&&delete g;a!=void 0&&a!=null&&delete a}
function loadShavingReviews(b,g,a,e){var c=[["Product Type","TYPE"],["Review Grade","GRADE"],["In Den","DEN"]],h=[["Review Date",0],["Review Grade",1]];HG_Journal_clearFilterValue();var j=document.getElementById("review_controls");j.innerHTML="";var f=document.createElement("div"),d=document.createElement("span");d.appendChild(document.createTextNode("Group:"));f.appendChild(d);var l=document.createElement("select");l.setAttribute("onchange","loadShavingReviews(0, 'DESC', this.value, null); refreshReviews(0);");
for(d=0;d<c.length;d++){var i=document.createElement("option");a.toLowerCase()==c[d][1].toLowerCase()&&i.setAttribute("selected","true");i.setAttribute("value",c[d][1]);i.appendChild(document.createTextNode(c[d][0]));l.appendChild(i)}f.appendChild(l);j.appendChild(f);c=document.createElement("div");d=document.createElement("span");d.appendChild(document.createTextNode("Sort:"));c.appendChild(d);for(d=0;d<h.length;d++)d!=0&&c.appendChild(document.createTextNode(" | ")),f=document.createElement("a"),
f.setAttribute("onclick","loadShavingReviews("+h[d][1]+', "'+(g=="DESC"?"ASC":"DESC")+'", "'+a+'", '+(e==null?"null":'"'+e+'"')+"); refreshReviews();"),f.appendChild(document.createTextNode(h[d][0])),c.appendChild(f),b==h[d][1]&&(f=document.createElement("img"),f.setAttribute("class","sort_arrow"),f.setAttribute("src","img/sort_"+(g=="ASC"?"up":"down")+".png"),c.appendChild(f));j.appendChild(c);h=document.getElementById("review_tabs");h.innerHTML="";j=[];d=0;switch(a.toLowerCase()){case "grade":d=
grade_scale.length-1;break;case "den":d=2;break;default:d=PRODUCT_CATEGORIES.length-1}for(;d>=0;d--)j[d]=null;switch(b){case 0:g=="ASC"?ShavingReviewedProducts.sort(function(a,b){return a.ReviewDate.getTime()==b.ReviewDate.getTime()?a.Grade-b.Grade:b.ReviewDate.getTime()-a.ReviewDate.getTime()}):sortProducts();break;case 1:sortProducts("Grade"),console.log("Sorted by grade: ",ShavingReviewedProducts.length)}f=c=null;displayed_reviews=0;for(b=ShavingReviewedProducts.length-1;b>=0;b--)if(d=ShavingReviewedProducts[b],
!(e!=void 0&&e!=null&&!eval(e))){displayed_reviews++;g=document.createElement("div");g.setAttribute("class","review_entry");d.Grade>-1&&setStyle(g,'background-image: url("img/shave_grade_'+grade_scale[d.Grade].toLowerCase()+'.png");');c=document.createElement("table");f=document.createElement("input");f.setAttribute("id","current_pic_"+b);f.setAttribute("type","hidden");f.setAttribute("value","0");c.appendChild(f);l=document.createElement("tr");i=document.createElement("td");f=document.createElement("img");
f.setAttribute("id","review_pic_"+b);d.Pictures!=null&&d.Pictures.length>0&&d.Pictures[0]!=null?(f.setAttribute("src",d.Pictures[0].getURL(PIC_SIZE_THUMB)),f.setAttribute("onclick","viewReviewSlideshow("+b+")")):f.setAttribute("src","img/default.png");i.appendChild(f);l.appendChild(i);c.appendChild(l);if(d.Pictures.length>1){var l=document.createElement("tr"),i=document.createElement("td"),f=document.createElement("span"),k=document.createElement("img");k.setAttribute("src","img/pics_arrow_left.png");
k.setAttribute("title","Previous picture");k.setAttribute("onclick","viewReviewPicture("+b+", -1)");f.appendChild(k);var m=document.createElement("span"),k=document.createElement("img");k.setAttribute("src","img/pics_arrow_right.png");k.setAttribute("title","Next picture");k.setAttribute("onclick","viewReviewPicture("+b+", 1)");m.appendChild(k);i.appendChild(f);i.appendChild(m);l.appendChild(i);c.appendChild(l)}g.appendChild(c);l=document.createElement("table");c=document.createElement("tr");f=document.createElement("td");
i=d.getName!=void 0?d.getName():d;f.appendChild(document.createTextNode(i));f.setAttribute("onclick",'tabsObj.ToggleTab(0); filterData("'+i.replace(/'/,"\\'").replace(/ \(.*\)/,"")+'");');f.setAttribute("title","View journal entries where this product was used!");d.inDen||(i=document.createElement("span"),i.appendChild(document.createTextNode("X")),f.appendChild(i));c.appendChild(f);l.appendChild(c);c=document.createElement("tr");f=document.createElement("td");i="Purchased";d.PurchaseDate!=null&&
(i+=" on "+HG_formatDate(d.PurchaseDate));d.Location!=null&&(i+=" from "+d.Location);d.Price!=null&&(i+=" for $"+d.Price);i.replace(/Purchased/,"").length>0&&f.appendChild(document.createTextNode(i));c.appendChild(f);l.appendChild(c);i=d.Grades;k=PRODUCT_GRADES[PRODUCT_CATEGORIES.indexOf(d.Type.toLowerCase())];if(i!=null&&i.length>0){for(var i=i.split(";"),c=document.createElement("tr"),f=document.createElement("td"),m=document.createElement("table"),n=Math.ceil(k.length/2),t=0,p=null,s=0;s<k.length;s++){var q=
k[s],r=i[s];t%n==0&&(p=document.createElement("tr"));var o=document.createElement("td");o.innerHTML=q;p.appendChild(o);q=document.createElement("td");o=document.createElement("img");grade_scale[r]!=void 0?o.setAttribute("src","img/shave_grade_"+grade_scale[r].toLowerCase()+".png"):o.setAttribute("src","img/shave_grade_meh_dark.png");o.setAttribute("title",grade_scale[r]);q.appendChild(o);p.appendChild(q);t%n==0&&m.appendChild(p);t++}f.appendChild(m);c.appendChild(f);l.appendChild(c)}if(d.ReviewComments!=
null)c=document.createElement("tr"),f=document.createElement("td"),f.innerHTML=d.ReviewComments,f.insertBefore(document.createElement("hr"),f.firstChild),c.appendChild(f),l.appendChild(c);g.appendChild(l);d=-1;switch(a.toLowerCase()){case "grade":d=ShavingReviewedProducts[b].Grade;d<0&&(d=0);break;case "den":d=ShavingReviewedProducts[b].inDen?0:1;break;default:d=PRODUCT_CATEGORIES.indexOf(ShavingReviewedProducts[b].Type.toLowerCase())}if(d>=0&&j[d]==null){c="";l=document.createElement("span");l.setAttribute("class",
"tab_name");switch(a.toLowerCase()){case "grade":c=i=grade_scale[d].toLowerCase();f=document.createElement("img");f.setAttribute("src","img/shave_grade_"+i+".png");setStyle(f,"height: 14px; width: 14px;");l.appendChild(f);break;case "den":f=d==0?"In Den":"Not In Den";c=d==0?"in_den":"not_in_den";l.appendChild(document.createTextNode(f));break;default:f=-1,f=PRODUCT_CATEGORIES[d],i="s",f=="brush"&&(i="es"),c=f+i,l.appendChild(document.createTextNode(f.charAt(0).toUpperCase()+f.substring(1)+i))}f=document.createElement("div");
f.setAttribute("class","tab_content");f.setAttribute("id","reviews_"+c);j[d]=document.createElement("div");j[d].setAttribute("class","tab");j[d].appendChild(l);j[d].appendChild(f)}j[d]!=null&&j[d].firstChild.nextSibling.appendChild(g)}a.toLowerCase()=="grade"&&(j=j.reverse());for(d=j.length-1;d>=0;d--)j[d]!=null&&h.insertBefore(j[d],h.firstChild)}var journalNav_Enabled=!1,journalNav_Current=-1,journalNav_Table=null,journalNav_Entries=null,displayed_entries=0;
function journalNav_display(b){toggleJournalExpand(!1);if(journalNav_Entries==null)journalNav_Table==null&&(journalNav_Table=document.getElementById("journal")),journalNav_Entries=journalNav_Table.children;var g=journalNav_Entries[b+1];toggleEntryDetails(g,!0);journalNav_Current=b;b=findElemPos(g);journalNav_Table.parentNode.scrollTop=b[1]-150}
function journalKeyboardNav(b){if(b=b?b:window.event?window.event:null)switch(b=b.charChode?b.charCode:b.keyCode?b.keyCode:b.which?b.which:0,b){case 74:case 75:var g=1;b==75&&(g=-1);b=(eval(journalNav_Current)+eval(g))%ShavingJournalEntries.length;b<0&&(b=ShavingJournalEntries.length-1);journalNav_display(b);break;case 187:case 189:tabsObj.CurrentTab==0&&toggleJournalExpand(b==187?!0:!1)}}function enableJournalNav(){journalNav_Enabled||(AddOKDListener(journalKeyboardNav),journalNav_Enabled=!0)}
function disableJournalNav(){journalNav_Enabled&&(RemoveOKDListener(journalKeyboardNav),journalNav_Enabled=!1)}var prodPreview=null;
function loadProductPreview(b,g){for(var a=b.parentNode.parentNode.parentNode.getElementsByTagName("tr"),e=a.length;e>=0;e--)if(!(a[e]==void 0||a[e]==null)){var c=a[e].getAttribute("class");if(c!=null&&c.indexOf("entry_full_hide")!=-1)return}prodPreview==null&&(prodPreview=document.getElementById("journal_product_preview"));a=ShavingReviewedProducts[g];if(a!=null&&(prodPreview.innerHTML="",console.log("loadProductPreview()",g,a.getName(),a),e=null,a.Pictures.length>0&&(e=document.createElement("img"),
e.setAttribute("src",a.Pictures[0].getURL(PIC_SIZE_THUMB))),c=null,a.Grade>-1&&(c=document.createElement("img"),c.setAttribute("src","img/shave_grade_"+grade_scale[a.Grade].toLowerCase()+".png")),e!=null||c!=null))e!=null&&prodPreview.appendChild(e),c!=null&&prodPreview.appendChild(c),a=findMousePos(),setStyle(prodPreview,"top: "+(a[1]+6)+"px; left: "+(a[0]+2)+"px; visibility: visible;")}
function hideProductPreview(){prodPreview==null&&(prodPreview=document.getElementById("journal_product_preview"));setStyle(prodPreview,"visibility: hidden;")}
function renderShavingJournalEntry(b,g){var a=null,e=null,c=[[["Razor","Blade","Strop"],!1],[["Brush","Soap","Cream"],!1],[["Preshave","Aftershave"],!0],[["Grades","AdjustableSetting","NumPasses"],!0]];setStyle(b,'background-image: url("img/shave_grade_'+g.Grade.toLowerCase()+'.png");');for(var h=document.createElement("table"),j=!1,f=0;f<c.length;f++){a=document.createElement("tr");c[f][1]&&a.setAttribute("class","entry_full entry_full_hide");for(var d=0;d<c[f][0].length;d++){var l=!1,i=c[f][0][d],
k=g[i];k!=null&&k.getName!=void 0&&(k=k.getName(),l=!0);if(!(i=="AdjustableSetting"&&k==null)){switch(i){case "NumPasses":i="Passes";break;case "AdjustableSetting":i="Adjustable Setting";break;case "Strop":if(!j)continue;break;case "Blade":if(k==null||k.length<=0){j=!0;continue}break;case "Soap":case "Cream":if(k==null||k.length<=0)continue;break;default:k!=null&&(k=k.toString())}e=document.createElement("td");e.innerHTML=i+":";e.setAttribute("class","journal_details_label");a.appendChild(e);if(i==
"Grades"){var e=document.createElement("td"),m=document.createElement("table");m.setAttribute("class","entry_grades");var n=g[i],t=0,p;for(p in n)t++;var s=Math.ceil(t/2),q=0,r=null;for(p in n){q%s==0&&(r=document.createElement("tr"));var o=document.createElement("td");o.innerHTML=p;r.appendChild(o);var v=document.createElement("td"),u=document.createElement("img");u.setAttribute("src","img/shave_grade_"+grade_scale[n[p]].toLowerCase()+".png");u.setAttribute("title",grade_scale[n[p]]);v.appendChild(u);
r.appendChild(v);q%s==0&&m.appendChild(r);q++;o!=void 0&&delete o;v!=void 0&&delete v;u!=void 0&&delete u}e.appendChild(m);a.appendChild(e);m!=void 0&&delete m;n!=void 0&&delete n;t!=void 0&&delete t;s!=void 0&&delete s;q!=void 0&&delete q;r!=void 0&&delete r}else{e=document.createElement("td");if(i=="Number of Passes")e.innerHTML=k;else if(k!=null&&k.length>0)l?(m=document.createElement("span"),n=ShavingReviewedProducts.indexOf(g[i.replace(/\//,"")]),m.innerHTML=k,m.setAttribute("onclick","tabsObj.ToggleTab(1); filterData('"+
k.replace(/ \(.*\)/,"")+"');"),n>=0&&(m.setAttribute("onmouseover","loadProductPreview(this, "+n+")"),m.setAttribute("onmouseout","hideProductPreview()")),e.appendChild(m)):e.innerHTML=k;a.appendChild(e)}l!=void 0&&delete l;i!=void 0&&delete i;k!=void 0&&delete k}}h.appendChild(a)}c=document.createElement("span");c.setAttribute("class","entry_full entry_full_hide");c.innerHTML="<hr />"+g.Notes;d=null;ShavingAlbum!=null&&(d=ShavingAlbum.getPicture("SOTD_"+HG_formatDate(g.Date,"%Y%M%D")+".jpg"));d!=
null&&(f=document.createElement("img"),f.setAttribute("src",d.getURL(PIC_SIZE_SOTD)),d=document.createElement("center"),d.appendChild(f),c.appendChild(document.createElement("br")),c.appendChild(document.createElement("br")),c.appendChild(d),f=document.createElement("div"),f.setAttribute("class","journal_sotd_camera"),d=document.createElement("img"),d.setAttribute("src","img/camera.png"),setStyle(d,"width: 16px"),f.appendChild(d),b.appendChild(f));b.appendChild(h);b.appendChild(c);a!=void 0&&delete a;
e!=void 0&&delete e;h!=void 0&&delete h;j!=void 0&&delete j;return!0}
function loadForms(){init_form("journal_form_date");loadUsedProducts();createJournalGradeScales();for(var b=document.getElementById("forms").getElementsByTagName("div"),g=b.length-1;g>=0;g--){var a=b[g].getAttribute("class");if(a!=null&&a.search("prod_type_lists")!=-1)for(var a=0,e=b[g].getElementsByTagName("select"),c=e.length-1;c>=0;c--){var h=e[c].clientWidth;h>a&&(setStyle(b[g],"width: "+h+"px !important;"),a=h)}}init_form("review_form_date");loadReviewGrades("Razor","review_grade_scales");b=
document.getElementById("review_entry_id");if(b!=null)b.value=HG_getNextProductID(ShavingReviewedProducts)}
function filterData(b){var g=tabsObj.CurrentTab,a=null,e=null,c=null;switch(g){case 1:e="reviewData";c=ShavingReviewedProducts[0];break;case 2:case 0:e="entries[i]",c=ShavingJournalEntries[0]}console.log("HERE ("+g+"): ",b,e);if(b!=null&&e!=null){console.log("R FILTER: ",b);var a=[],h;for(h in c)h=="equals"||h=="contains"||h=="search"||h.charAt(0)=="_"||a.push(h);a=parseFilter(e,a,b);console.log("R PARSED FILTER: ",a);document.getElementById("hg_journal_filter_exp").value=b}switch(g){case 0:loadShavingJournal(0,
"DESC",a);filterMsg.innerHTML="Showing "+displayed_entries+" entries";break;case 1:loadShavingReviews(0,"DESC","TYPE",a),refreshReviews(),filterMsg.innerHTML="Showing "+displayed_reviews+" reviews",tabsObj.NestedTabs[1].ToggleTab(0)}}var filter_operators=["||","&&"];
function parseFilter(b,g,a){console.log("parseFilter("+a+")");var e="",c="||",h="";if(a==null)return e;for(var j=0;j<filter_operators.length;j++)if(c=filter_operators[j],a.indexOf(c)!=-1){h=a.split(c);break}if(h.length>0)for(a=0;a<h.length;a++)a!=0&&(e+=" "+c+" "),e+=parseFilter(b,g,h[a].replace(/^\s+/,"").replace(/\s+$/,""));else if(a.indexOf(":"))if(a=a.replace(/\s*:\s*/,":").split(":"),a.length==1||a[0]=="*"){e=a.length==1?a[0]:a[1];e='"'+e+'"';c="(";for(a=g.length-1;a>=0;a--)h=b+'["'+g[a]+'"]',
c+="("+h+" != null && (("+h+".search) ? ("+h+".search("+e+") != -1) : ("+h+".toString().search("+e+") != -1)))",a>0&&(c+=" || ");c+=")";return c}else if(a[0]=a[0].indexOf("/")!=-1?'["'+a[0]+'"]':"."+a[0],b+=a[0],a[0].indexOf("Date")!=-1&&(b="HG_formatDate("+b+")"),a[1]=a[1].replace(/'/,"'"),a[0]!=".*")return"("+b+" == "+a[1]+" || ("+b+".search && "+b+".search('"+a[1]+"') != -1))";return e}var filter_busy=!1;
function filterFocusToggle(b){filterBox==null&&(filterBox=document.getElementById("hg_journal_filter_exp"));var g=filterBox.getAttribute("class");b?(filterBox.focus(),filterBox.select(),filterBox.setAttribute("class",g+" list_filter_focus"),filter_busy=!0):(filterBox.blur(),filterBox.setAttribute("class",g.replace(" list_filter_focus","")),setStyle(filterBox,"background-color: "+(filterBox.value.length<=0?"#fff":"#FFEA84")),filter_busy=!1);switch(tabsObj.CurrentTab){case 1:tabsObj.NestedTabs[1].IgnoreKeyboard=
b;case 0:tabsObj.IgnoreKeyboard=b}}var active_filters=[null,null,null];
function onTabToggle(b,g){console.log("onTabToggle("+b+", "+g+")");filterBox==null&&(filterBox=document.getElementById("hg_journal_filter_exp"));var a=document.getElementById("hg_journal_filter");filterMsg==null&&(filterMsg=a.getElementsByTagName("span")[0]);g==0?enableJournalNav():disableJournalNav();var e=["list_creams","list_soaps","list_blades","list_strops"];switch(b){case 0:case 1:if(filterBox.value!=null&&filterBox.value.length>0)active_filters[b]=filterBox.value;break;case 3:for(var c=e.length-
1;c>=0;c--){var h=document.getElementById(e[c]),j=h.getAttribute("class");j!=null&&j.search("sel_prod_type_list")!=-1&&h.setAttribute("class",j.replace(/sel_prod_type_list/g,""))}}switch(g){case 1:case 0:if(active_filters[g]!=null)filterBox.value=active_filters[g],active_filters[g]=null;else if(filterBox.value.length>0)filterBox.value="";setStyle(a,"visibility: visible;");setStyle(filterMsg,"visibility: visible;");setStyle(filterBox,"visibility: visible;background-color: "+(filterBox.value.length<=
0?"#fff":"#FFEA84"));switch(g){case 0:filterMsg.innerHTML="Showing "+displayed_entries+" entries";break;case 1:filterMsg.innerHTML="Showing "+displayed_reviews+" reviews";break;default:filterMsg.innerHTML=""}tabsObj.IgnoreKeyboard=!1;if(tabsObj.NestedTabs.length>=4)tabsObj.NestedTabs[3].IgnoreKeyboard=!1;break;case 3:for(c=e.length-1;c>=0;c--)h=document.getElementById(e[c]+"_label").getAttribute("class"),h!=null&&h.search("sel_prod_type_label")!=-1&&(h=document.getElementById(e[c]),j=h.getAttribute("class"),
j!=null&&j.length>0?j+=" ":j==null&&(j=""),h.setAttribute("class",j+"sel_prod_type_list"));e=ShavingJournalEntries[ShavingJournalEntries.length-1];console.log("  >> LAST ENTRY: ",e);e.Blade==null?switchToStrop():switchToBlade();e.Soap==null?switchToCream():switchToSoap();pw_sel_obj==null&&(pw_sel_obj=PicasaWeb_PicSelect(ShavingAlbum,document.getElementById("pictures_select"),null,!0));default:setStyle(a,"visibility: hidden;"),setStyle(filterMsg,"visibility: hidden;"),setStyle(filterBox,"visibility: hidden;"),
tabsObj.IgnoreKeyboard=!0,tabsObj.NestedTabs[3].IgnoreKeyboard=!0}}
function loadExtras(){sortJournalEntries();sortProducts();(ShavingCombos==null||ShavingCombos.length<=0)&&createShavingCombos();loadTrends();var b=null;if(window.location.hostname=="localhost")loadForms();else{var b=["Submit Entry","TODO"],g=document.getElementById("forms");g.parentNode.parentNode.removeChild(g.parentNode)}HG_loadJournalViews([new HG_Journals_View("ShavingJournalEntries",["Date","Grade"],"journal_tab","renderShavingJournalEntry"),new HG_Journals_View("ShavingReviewedProducts",null,
"review_tabs",function(){loadShavingReviews(0,"DESC","TYPE",null)})],b);document.getElementById("journal_scroller");HG_Journal_tabsObj.AddToggleListener(onTabToggle);enableJournalNav()}function HG_Journal_local_init(){getShavingData(loadExtras)};
