var hofLyr=null,metricCharts=[{name:"Soap vs. Cream",type:"p3",size:"320x130",color:"eee686",values:[{label:"Soaps",value:0},{label:"Creams",value:0}]},{name:"Straight vs. DE",type:"p3",size:"320x130",color:"FF0C0C",values:[{label:"DE",value:0},{label:"Straight",value:0}]},{name:"Average grade per week day",type:"bvs",size:"320x130",color:"4d89f9",values:[{label:"Sun",value:0},{label:"Mon",value:0},{label:"Tue",value:0},{label:"Wed",value:0},{label:"Thu",value:0},{label:"Fri",value:0},{label:"Sat",
value:0}]},{name:"Brush Usage",type:"bhs",size:"620x180",color:"3879D9",values:[]},{name:"Soap Usage",type:"bhs",size:"620x480",color:"3879D9",values:[]},{name:"Cream Usage",type:"bhs",size:"620x160",color:"3879D9",values:[]},{name:"Vendor Stats",type:"p3",size:"320x130",color:"eee686",values:[{label:"Soaps",value:0},{label:"Creams",value:0}]}];
function createChart(a){var d=document.createElement("img"),c="http://www.google.com/chart?chtt="+a.name.replace(/\s/g,"+")+"&cht="+a.type+"&chs="+a.size+"&",b="",f=a.color;switch(a.type){case "p":case "p3":for(var g="",h=0;h<a.values.length;h++){var e=a.values[h];h!==0&&(g+="|",b+=",");g+=e.label;e=eval(e.value);b+=e}c+="chl="+g+"&";break;case "bvs":case "bhs":c+="chbh=24,6&chxt=x,y&";c+="chxs=0,000000,12,0,lt|1,000000,12,1,lt&";for(var g="",k=0,l=0,h=0;h<a.values.length;h++)e=a.values[h],h!==0&&
(g+="|",b+=","),g+=e.label,e=eval(e.value),b+=e,e<k&&(k=e),e>l&&(l=e);for(var h="",e=l-k>5,j=k;j<=l;j++)if(!e||!(j%2!=0&&j>k&&j<l))h+=j+"|";switch(a.type){case "bvs":c+="&chxl=0:|"+g+"|1:|"+h;break;case "bhs":a="";g=g.split("|");for(e=g.length-1;e>=0;e--)a+=g[e],e!=0&&(a+="|");c+="&chxl=0:|"+h+"|1:|"+a}c+="&chds="+k+","+l+"&chm=N,000000,0,-1,11&"}c+="chco&="+f+"&chd=t:"+b;d.setAttribute("src",c);return d}function loadTrends(){loadHOF();loadCharts()}
function loadCharts(){for(var a=document.getElementById("charts"),d=metricCharts[0],c=metricCharts[1],b=metricCharts[2],f=metricCharts[3],g=metricCharts[4],h={},e={},k=0,l=0,j=0,o=[0,0,0,0,0,0,0],m=ShavingJournalEntries.length-1;m>=0;m--){var i=ShavingJournalEntries[m];j++;if(i.Soap!=null){var n=i.Soap.getName!=void 0?i.Soap.getName():i.Soap;n!=null&&n.search(/sample/i)==-1&&(e.length<0||e[n]==null?e[n]=1:e[n]!=null&&e[n]++);k++}i.Cream!=null&&l++;i.Razor.getName().search(/straight/i)!=-1?c.values[1].value++:
c.values[0].value++;b.values[i.Date.getDay()].value+=eval(grade_scale.indexOf(i.Grade));o[i.Date.getDay()]++;i=i.Brush!=null?i.Brush.getName():null;i!=null&&(h.length<0||h[i]==null?h[i]=1:h[i]!=null&&h[i]++)}d.values[0].value=k;d.values[0].label+=" ["+Math.round(k/j*100)+"%]";d.values[1].value=l;d.values[1].label+=" ["+Math.round(l/j*100)+"%]";a.appendChild(createChart(d));c.values[0].label+=" ["+Math.round(c.values[0].value/j*100)+"%]";c.values[1].label+=" ["+Math.round(c.values[1].value/j*100)+
"%]";a.appendChild(createChart(c));for(m=b.values.length-1;m>=0;m--)b.values[m].value=Math.ceil(b.values[m].value/o[m]);a.appendChild(createChart(b));for(var p in h)f.values.push({label:p,value:h[p]});a.appendChild(createChart(f));for(var q in e)g.values.push({label:q,value:e[q]});a.appendChild(createChart(g))}
function _createPropertyRow(a,d){var c=d[a.replace(/(\/|-|\s)/,"")];if(c==null||c.length<=0||c=="N/A")return document.createTextNode(" ");var b=document.createElement("tr"),f=document.createElement("td");f.appendChild(document.createTextNode(a+":"));b.appendChild(f);f=document.createElement("td");f.appendChild(document.createTextNode(c.getName!=void 0?c.getName():c));b.appendChild(f);return b}
function _createPropertyRow3(a,d,c){a=d[a.replace(/(\/|-|\s)/,"")];if(a==null||a.length<=0||a=="N/A")return document.createTextNode(" ");var d=document.createElement("tr"),b=document.createElement("td");setStyle(b,"text-align: "+(c?"left":"right"));var f=document.createElement("img");console.log(a);a.Pictures?f.setAttribute("src",a.Pictures[0]):f.setAttribute("src","img/shave_grade_meh.png");setStyle(f,"width: 80px;");var g=document.createElement("span");setStyle(g,"margin-top: 10px; vertical-align: top;");
b.appendChild(document.createTextNode(a.getName!=void 0?a.getName():a));c?(b.appendChild(f),b.appendChild(g)):(b.appendChild(g),b.appendChild(f));d.appendChild(b);return d}
function _createPropertyRow_new(a,d,c){a=d[a.replace(/(\/|-|\s)/,"")];if(a==null||a.length<=0||a=="N/A")return document.createTextNode(" ");var d=document.createElement("div"),b=c?"left":"right";setStyle(d,"text-align: "+b+"; float: "+b+";");b=document.createElement("img");a.Pictures&&b.setAttribute("src",a.Pictures[0]);setStyle(b,"width: 120px;");var f=document.createElement("span");setStyle(f,"margin-top: 10px; vertical-align: "+(c?"top":"bottom")+";");cell.appendChild(document.createTextNode(a.getName!=
void 0?a.getName():a));c?(d.appendChild(b),d.appendChild(f)):(d.appendChild(f),d.appendChild(b));return d}
function loadHOF(){hofLyr==null&&(hofLyr=document.getElementById("combo_hof"));sortShavingCombos();hofLyr.innerHTML="";for(var a=null,d=getAverageComboGrade(),c=ShavingCombos.length-1;c>=0;c--){var b=ShavingCombos[c];if(!(b.Dates.length<3||b.Grade<=d)){a=document.createElement("table");a.appendChild(_createPropertyRow("Razor",b));b.Blade!=null?a.appendChild(_createPropertyRow("Blade",b)):a.appendChild(_createPropertyRow("Strop",b));a.appendChild(_createPropertyRow("Brush",b));b.Soap!=null?a.appendChild(_createPropertyRow("Soap",
b)):a.appendChild(_createPropertyRow("Cream",b));for(var f="",g=b.Dates.length-1;g>=0;g--)f+="Date: "+HG_formatDate(b.Dates[g])+"",g!=0&&(f+=" || ");a.setAttribute("onclick",'tabsObj.ToggleTab(0); filterData("'+f+'");');a.setAttribute("title","View journal entries for this combo");hofLyr.appendChild(a)}}}function getAverageComboGrade(){for(var a=0,d=ShavingCombos.length-1;d>=0;d--)a+=ShavingCombos[d].Grade;return Math.floor(a/ShavingCombos.length)};
