GSpreadsheetRetrieval.prototype=new GoogleDataRetrieval;function GSpreadsheetRetrieval(a,b,c){this.URL=a;this.UserCallback=b;this.UserCallbackArguments=c;this.Service="wise";this.ArrayPos=-1;this.httpReq=new libHTTPRequest}
GSpreadsheetRetrieval.prototype.retrieveEntries=function(a){for(var b=[],a=GoogleDataRetrieval.prototype.retrieveEntries(a),c=a.length-1;c>=0;c--)for(var d=a[c].length-1;d>=0;d--)if(a[c][d].content)content=a[c][d].content.$,content!=null&&b.push(this.createObjectFromEntry(content)),delete content;delete a;return b};var GoogleDataRetrievals=[];function GoogleDataRetrieval(a,b,c,d){this.ArrayPos=-1;this.URL=a;this.Service=b;this.UserCallback=c;this.UserCallbackArguments=d;this.httpReq=new libHTTPRequest}GoogleDataRetrieval.prototype.createObjectFromEntry=function(a){var b=a,a=a.match(/,\s*[a-z_]*:\s/g);a.push(b.match(/^[a-z_]*:\s/)[0]);for(var c=null,d=a.length-1;d>=0;d--)c=a[d],b=b.replace(c,'"'+c.replace(/:\s/,'":').replace(/,\s/,', "')+'"'),delete c;delete a;return eval("[{"+b+'"}]')[0]};
GoogleDataRetrieval.prototype.retrieveEntries=function(a){var b=[];if(a.entry)b.push(a.entry["#"]);else if(a.feed){for(var a=a.feed["#"],c=null,d=a.length-1;d>=0;d--)a[d].entry&&(c=a[d].entry["#"],b.push(c));delete a}return b};
GoogleDataRetrieval.prototype.Callback=function(a){var b=null;try{a!="Token invalid"&&(a=a.replace(/\s/g," "),b=this.retrieveEntries(eval(a)[0]))}catch(c){console.log("  RET: ",a),console.log("GoogleDataRetrieval.Callback: err = "+c),console.trace(),b=null}finally{this.UserCallbackArguments!=null?this.UserCallback(b,this.UserCallbackArguments):this.UserCallback(b)}};
GoogleDataRetrieval.prototype.Retrieve=function(a){this.httpReq.getData(this.URL,"gs="+this.Service,function(b){var c=GoogleDataRetrievals[a];c!=null&&c!=void 0&&c.Callback(b)},!0)};function getGoogleData(a){a.ArrayPos=GoogleDataRetrievals.length;GoogleDataRetrievals.push(a);a.Retrieve(a.ArrayPos)}GSpreadsheetRetrieval.prototype=new GoogleDataRetrieval;
function GSpreadsheetRetrieval(a,b,c){this.URL=a;this.UserCallback=b;this.UserCallbackArguments=c;this.Service="wise";this.ArrayPos=-1;this.httpReq=new libHTTPRequest}GSpreadsheetRetrieval.prototype.retrieveEntries=function(a){for(var b=[],a=GoogleDataRetrieval.prototype.retrieveEntries(a),c=a.length-1;c>=0;c--)for(var d=a[c].length-1;d>=0;d--)if(a[c][d].content)content=a[c][d].content.$,content!=null&&b.push(this.createObjectFromEntry(content)),delete content;delete a;return b};var LibSlideshow_Active=[];function LibSlideshow(a){this._ThumbnailsLayer=this._ImgLayer=this._MainLayer=null;this._isListening=!1;this._previousListener=null;this.Pictures=a;this.CurrentPicture=-1;a!=null&&this.LoadLarge()}LibSlideshow_KeyboardHandler=function(a){for(var a=a?a:window.event?window.event:null,b=LibSlideshow_Active.length-1;b>=0;b--){var c=LibSlideshow_Active[b];c._isListening&&c._fireKeyboardEvent(a)}};
LibSlideshow.prototype._fireKeyboardEvent=function(a){if(a)switch(a.charChode?a.charCode:a.keyCode?a.keyCode:a.which?a.which:0){case 72:this.Previous();break;case 76:this.Next();break;case 27:this.Exit()}};
LibSlideshow.prototype.ViewPicture=function(a){if(this._ImgLayer!=null){var b="";if(this._ThumbnailsLayer!=null){var c=this._ThumbnailsLayer.getElementsByTagName("img");if(this.CurrentPicture>=0){var d=c[this.CurrentPicture],b=d.getAttribute("class");b!=null&&b.length>0&&d.setAttribute("class",b.replace(/ current/,""))}}this._ImgLayer.setAttribute("src",this.Pictures[a]);this.CurrentPicture=a;this._ThumbnailsLayer!=null&&(a=c[this.CurrentPicture],b=a.getAttribute("class"),b==null&&(b=""),a.setAttribute("class",
b+" current"))}};LibSlideshow.prototype._slidePicture=function(a,b){if(a!=null){var c=(eval(a.CurrentPicture)+eval(b))%a.Pictures.length;c<0&&(c=a.Pictures.length-1);return a.ViewPicture(c)}};LibSlideshow.prototype.Next=function(a){if(!(a<0||a>LibSlideshow_Active.length))return a=LibSlideshow_Active[a],a==null||a.Pictures.length<=1?void 0:a._slidePicture(a,1)};
LibSlideshow.prototype.Previous=function(a){if(!(a<0||a>LibSlideshow_Active.length))return a=LibSlideshow_Active[a],a==null||a.Pictures.length<=1?void 0:a._slidePicture(a,-1)};LibSlideshow.prototype.Next=function(){return this._slidePicture(this,1)};LibSlideshow.prototype.Previous=function(){return this._slidePicture(this,-1)};
LibSlideshow.prototype.Exit=function(){if(this._previoustListener)document.onkeydown=this._previoustListener;this._MainLayer.parentNode.removeChild(this._MainLayer);for(var a=[],b=LibSlideshow_Active.length-1;b>=0;b--)LibSlideshow_Active[b]!=this&&a.unshift(LibSlideshow_Active[b]);LibSlideshow_Active=a};
LibSlideshow.prototype.LoadLarge=function(){LibSlideshow_Active.push(this);var a=LibSlideshow_Active.length-1,b=document.createElement("div");b.setAttribute("class","LibSlideshow");b.setAttribute("LibSlideshow_idx",a);var c=document.createElement("div");c.setAttribute("class","background");b.appendChild(c);var d=document.createElement("div"),c=document.createElement("img");d.appendChild(c);b.appendChild(d);d=null;if(this.Pictures.length>1){document.createElement("span").setAttribute("class","LibSlideshow_Close");
document.createElement("span").setAttribute("class","LibSlideshow_Previous");document.createElement("span").setAttribute("class","LibSlideshow_Next");for(var d=document.createElement("div"),f=this.Pictures.length-1;f>=0;f--){var g=document.createElement("img");g.setAttribute("src",this.Pictures[f]);g.setAttribute("onclick","LibSlideshow_Active["+a+"].ViewPicture("+f+");");d.insertBefore(g,d.firstChild)}b.appendChild(d)}document.body.appendChild(b);this._MainLayer=b;this._ImgLayer=c;this._ThumbnailsLayer=
d;if(document.onkeydown!=null)this._previoustListener=document.onkeydown;document.onkeydown=LibSlideshow_KeyboardHandler;this._isListening=!0;this.Next()};function PicasaWeb_Pic(a){this.data=a;this.caption=this.url=this.name=this.id=null;this.height=this.width=0;this.loaded=!1;this._load()}PicasaWeb_Pic.prototype.isLoaded=function(){return this.loaded};PicasaWeb_Pic.prototype.getURL=function(a){var b=this.url;a!=void 0&&a!=null&&(b+="/s"+a);b+="/"+this.name;return b};
PicasaWeb_Pic.prototype._load=function(){if(!(this.data==null&&this.data==void 0)){for(var a=this.data.length-1;a>=0;a--){var b=this.data[a];if(b!=null)if(b.title)this.name=b.title.$;else if(b.id){if(b=b.id.$,b!=null&&b!=void 0)this.id=b.slice(b.lastIndexOf("/")+1)}else if(b.content&&b.content!=null)b=b.content["@"].src,this.url=b.substr(0,b.lastIndexOf("/"))}this.loaded=!0}};
function PicasaWeb_Album(a,b){this.ALBUM_PICS_URL="https://picasaweb.google.com/data/feed/api/user/"+a+"/albumid";this.user=a;this.data=b;this.name=null;this.id=-1;this.Pics=this.updated=this.summary=this.url=null;this._load()}PicasaWeb_Album.prototype.isLoaded=function(){return this.isLoaded(null)};PicasaWeb_Album.prototype.isLoaded=function(a){if(this.Pics==null)return!1;for(var b=this.Pics.length-1;b>=0;b--)if(!(a!=void 0&&a!=null&&this.Pics[b].name!=a)&&!this.Pics[b].isLoaded())return!1;return!0};
PicasaWeb_Album.prototype.Size=function(){return this.Pics==null?0:this.Pics.length};PicasaWeb_Album.prototype.getPicture=function(a){for(var b=this.Pics.length-1;b>=0;b--)if(this.Pics[b].name==a)return this.Pics[b];return null};PicasaWeb_Album.prototype._retrievePics=function(a){if(this.Pics==null||this.Pics==void 0)this.Pics=[];if(a!=null&&a.length>0)for(var b=a.length-1;b>=0;b--)a[b]!=null&&this.Pics.push(new PicasaWeb_Pic(a[b]))};
PicasaWeb_Album.prototype._load=function(){for(var a=this.data.length-1;a>=0;a--){var b=this.data[a];if(b!=null)if(b.title)this.name=b.title.$;else if(b.id)b=b.id.$,this.id=b.slice(b.lastIndexOf("/")+1),this.url=this.ALBUM_PICS_URL+"/"+this.id;else if(b.summary)this.summary=b.summary.$}if(!(this.name!="HG_Shaving"&&this.name!="HG_Tea"&&this.name!="Our First House")&&this.id!=null){PicasaWebObjects_retrieving.push(this);var c=PicasaWebObjects_retrieving.length-1;getGoogleData(new PicasaWebRetrieval(this.url,
function(a){var b=PicasaWebObjects_retrieving[c];(b!=null||b!=void 0)&&b._retrievePics(a)},null))}};function PicasaWeb(a){this.USER_ALBUMS_URL="https://picasaweb.google.com/data/feed/api/user/"+a+"&access=private";this.user=a;this.Albums=this.cover=null;this._load()}PicasaWeb.prototype.isLoaded=function(){return this.isLoaded(null)};
PicasaWeb.prototype.isLoaded=function(a){if(this.Albums==null)return!1;for(var b=this.Albums.length-1;b>=0;b--)if(!(a!=void 0&&a!=null&&this.Albums[b].name!=a)&&!this.Albums[b].isLoaded())return!1;return!0};PicasaWeb.prototype.getAlbum=function(a){if(this.Albums!=null)for(var b=this.Albums.length-1;b>=0;b--)if(this.Albums[b].name==a)return this.Albums[b];return null};
PicasaWeb.prototype._retrieveAlbums=function(a){if(this.Albums==null||this.Albums==void 0)this.Albums=[];if(a!=null&&a.length>0)for(var b=a.length-1;b>=0;b--)(a[b]!=null||a[b]!=void 0)&&this.Albums.push(new PicasaWeb_Album(this.user,a[b]))};PicasaWeb.prototype._load=function(){PicasaWebObjects_retrieving.push(this);var a=PicasaWebObjects_retrieving.length-1;getGoogleData(new PicasaWebRetrieval(this.USER_ALBUMS_URL,function(b){PicasaWebObjects_retrieving[a]._retrieveAlbums(b)},null))};
var PicasaWebObjects_retrieverCount=-1,PicasaWebObjects_retrieving=[];PicasaWebRetrieval.prototype=new GoogleDataRetrieval;function PicasaWebRetrieval(a,b,c){this.URL=a;this.UserCallback=b;this.UserCallbackArguments=c;this.Service="lh2";this.ArrayPos=-1;this.httpReq=new libHTTPRequest}function PicasaWeb_PicView(a,b){this.pic=a;this.elem=b;this.PIC_CLASSNAME="PicasaWeb_PicView";this.PIC_SIZE=300;this._load()}
PicasaWeb_PicView.prototype._load=function(){if(this.elem!=null){this.elem.innerHTML="";addClass(this.elem,this.PIC_CLASSNAME);var a=document.createElement("img");a.setAttribute("src",this.pic.getURL(this.PIC_SIZE));this.elem.appendChild(a)}};
function PicasaWeb_AlbumView(a,b,c){this.album=a;this.elem=b;this.display_header=c;this.pics_view=this.header_view=null;this.ALBUM_CLASSNAME="PicasaWeb_AlbumView";this.ALBUM_HEADER_CLASSNAME="PicasaWeb_AlbumView_Header";this.ALBUM_PICS_CLASSNAME="PicasaWeb_AlbumView_Pics";this._load()}
PicasaWeb_AlbumView.prototype._load=function(){if(this.elem!=null){this.elem.innerHTML="";addClass(this.elem,this.ALBUM_CLASSNAME);if(this.display_header){this.header_view=document.createElement("div");addClass(this.header_view,this.ALBUM_HEADER_CLASSNAME);var a=document.createElement("span");a.appendChild(document.createTextNode(this.album.name));this.header_view.appendChild(a);this.elem.appendChild(this.header_view)}this.pics_view=document.createElement("div");addClass(this.pics_view,this.ALBUM_PICS_CLASSNAME);
for(a=this.album.Pics.length-1;a>=0;a--){var b=document.createElement("span");new PicasaWeb_PicView(this.album.Pics[a],b);this.pics_view.insertBefore(b,this.pics_view.firstChild)}this.elem.appendChild(this.pics_view)}};function PicasaWeb_View(a,b){this.albums=a;this.elem=b;this.album_views=null;this.ALBUMS_CLASSNAME="PicasaWeb_View"}PicasaWeb_View.prototype._load=function(){this.elem.innerHTML="";addClass(this.elem,this.ALBUMS_CLASSNAME)};var PicasaWeb_PicSelectObjs=[];
function PicasaWeb_PicSelect(a,b,c,d){console.log("PicasaWeb_PicSelect()");a=new PicasaWeb_PicSelect_View(a,b,c);if(a==null)return[];console.log("   creating selection control");a.pos=PicasaWeb_PicSelectObjs.length;PicasaWeb_PicSelectObjs.push(a);a.show_header=!1;a.multiselect=d;a.load();return a}
function PicasaWeb_PicSelect_View(a,b,c){this.album=a;this.elem=b;this.pos=-1;this.thumb_size=50;this.multiselect=this.show_header=!0;this.callback=c;this.Selected=[];this.PICSELECT_CLASSNAME="PicasaWeb_PicSelect";this.PICSELECT_PICS_CLASSNAME="PicasaWeb_PicSelect_Pics";this.PICSELECT_PIC_CLASSNAME="PicasaWeb_PicSelect_Pic";this.PICSELECT_SELECTED_CLASSNAME="PicasaWeb_PicSelect_Pic_Selected";this.PICSELECT_HDR_CLASSNAME="PicasaWeb_PicSelect_Header";this.PICSELECT_BTN_CLASSNAME="PicasaWeb_PicSelect_Button"}
PicasaWeb_PicSelect_View.prototype.select=function(a,b){this.Selected.contains(a)?(this.Selected.splice(this.Selected.indexOf(a),1),removeClass(b,this.PICSELECT_SELECTED_CLASSNAME)):(this.Selected.push(a),addClass(b,this.PICSELECT_SELECTED_CLASSNAME),this.multiselect||this.close())};PicasaWeb_PicSelect_View.prototype.getSelected=function(){for(var a=[],b=0;b<this.Selected.length;b++)a.push(this.album.Pics[this.Selected[b]]);return a};
PicasaWeb_PicSelect_View.prototype.close=function(){if(this.elem!=null)this.elem.innerHTML="";this.callback!=null&&this.callback(this.getSelected())};
PicasaWeb_PicSelect_View.prototype.load=function(){if(this.album==null||this.elem==null)console.log("WTF?",this.album,this.elem);else{var a=document.createElement("div");addClass(a,this.PICSELECT_CLASSNAME);if(this.show_header){var b=document.createElement("div");addClass(b,this.PICSELECT_HDR_CLASSNAME);if(this.multiselect){var c=document.createElement("div");addClass(c,this.PICSELECT_BTN_CLASSNAME);c.setAttribute("onclick","PicasaWeb_PicSelectObjs["+this.pos+"].close()");c.appendChild(document.createTextNode("Done"));
b.appendChild(c)}c=document.createElement("div");c.appendChild(document.createTextNode(this.album.name+" ("+this.album.Pics.length+")"));b.appendChild(c);a.appendChild(b)}b=document.createElement("div");addClass(b,this.PICSELECT_PICS_CLASSNAME);for(var c=this.album.Pics,d=0;d<c.length;d++){var f=document.createElement("img");f.setAttribute("src",c[d].getURL(this.thumb_size));f.setAttribute("onclick","PicasaWeb_PicSelectObjs["+this.pos+"].select("+d+", this)");addClass(f,this.PICSELECT_PIC_CLASSNAME);
b.appendChild(f)}a.appendChild(b);this.elem.appendChild(a)}};var libHTTPRequest_Constants={MSXML_VERS:["MSXML2.XMLHttp.6.0","MSXML2.XMLHttp.5.0","MSXML2.XMLHttp.4.0","MSXML2.XMLHttp.3.0","MSXML2.XMLHttp","Microsoft.XMLHttp"],useActiveX:typeof ActiveXObject!="undefined",useDom:document.implementation&&document.implementation.createDocument,useXmlHttp:typeof XMLHttpRequest!="undefined"},libHTTPRequest_Requests=[];
function libHTTPRequest_DataManager(){this.Scripts=["http://"+window.location.hostname+"/sss/XDRequest.php"];this.StoreLocation="http://"+window.location.hostname+"/sss/gen"}
function libHTTPRequest(){this.Request=this.Callback=this.Options=this.URL=null;this.Store=!1;this.StoreFileName="libHTTPRequest";this.DataManager=new libHTTPRequest_DataManager;this.DataScript=null;this._XmlHttpReq=function(){if(typeof XMLHttpRequest!="undefined")return new XMLHttpRequest;else if(libHTTPRequest_Constants.useActiveX)for(var a=0;a<libHTTPRequest_Constants.MSXML_VERS.length;a++)try{return new ActiveXObject(libHTTPRequest_Constants.MSXML_VERS[a])}catch(b){}throw Error("XMLHttp object could not be created.");
};this.ping=function(a){var b=this._XmlHttpReq(),c=!1;b.open("GET",a,!1);try{b.send(null),b!=null&&b.readyState=="4"&&b.status>=200&&b.status<=207&&(c=!0)}catch(d){}return c};this._load=function(){for(var a=new libHTTPRequest_DataManager,b=0;b<a.Scripts.length;b++)if(this.ping(a.Scripts[b])){this.DataScript=a.Scripts[b];break}};this._load()}
libHTTPRequest._onreadystatechange=function(a){var b=libHTTPRequest_Requests[a],c=b.Request,d=b.Callback,b=b.Store;if(c!=null&&c.readyState=="4")switch(c.status){case 200:case 201:case 202:case 203:case 204:case 205:case 206:case 207:var f=null,f=c.responseXML&&c.responseXML.length>0?c.responseXML:c.responseText;f!=null&&d!=null?d(f):b&&libHTTPRequest._loadFromBackup(a);break;default:b&&libHTTPRequest._loadFromBackup(a)}};
libHTTPRequest._loadFromBackup=function(a){var b=libHTTPRequest_Requests[a],c=new libHTTPRequest_DataManager;this.StoreLocation="http://dl.dropbox.com/u/6524/hokiegeek.net/sss/gen";a=b.getXmlRequest("GET",c.StoreLocation+"/"+b.StoreFileName+".json",a);b.Request=a;a.send(null)};libHTTPRequest.prototype.getXmlRequest=function(a,b,c){var d=this._XmlHttpReq();d.onreadystatechange=function(){libHTTPRequest._onreadystatechange(c)};d.open(a,b,!0);return d};
libHTTPRequest.prototype.getData=function(a,b,c,d){if(a!=void 0){this.URL=a;this.Options=b;this.Callback=c;if(this.Store=d)c=a,a.indexOf("?")!=-1&&(c=a.substring(0,a.indexOf("?"))),c=c.replace(/https?:\/\//g,"").replace(/(\/|\.|\-|=|&)/g,"_"),this.StoreFileName+="__"+c,b+="&store="+this.StoreFileName;libHTTPRequest_Requests.push(this);this.Request=a=this.getXmlRequest("GET",this.DataScript+"?u="+a+"&"+b,libHTTPRequest_Requests.length-1);a.send(null)}};
libHTTPRequest.prototype.sendData=function(a,b){this.URL=a;this.Options=b;for(var c="",d=0;d<b.length;d++)d>0&&(c+="&"),c+=b[d];libHTTPRequest_Requests.push(this);d=this.getXmlRequest("POST",this.DataScript+"?u="+a,libHTTPRequest_Requests.length-1);d.setRequestHeader("Content-type","application/x-www-form-urlencoded");this.Request=d;d.send(c)};var LibTabs_Orientation={TOP:0,LEFT:1,BOTTOM:2,RIGHT:3},LibTabs_keyboardListeners=[];function LibTabs_tabsNav(a){for(var b=LibTabs_keyboardListeners.length-1;b>=0;b--)eval(LibTabs_keyboardListeners[b])._keyboardNav(a)}
function LibTabs(a,b,c,d,f){function g(a,b){this.name=a;this.content=b;this.visible=!1}this.ThisObj=a;this.ParentLyr=null;this.CurrentTab=-1;this.Tabs=[];this.Orientation=d==void 0?LibTabs_Orientation.TOP:d;this.NestedTabs=[];this._gutterWidth=0;this.IgnoreKeyboard=!1;this.ToggleListeners=[];this.ExcludedTabs=f;this.Reloaded=!1;this.TAB_NAME_SPACING=5;this._findPos=function(a){var b=etop=0;if(a.offsetParent){do b+=a.offsetLeft,etop+=a.offsetTop;while(a=a.offsetParent);return[b,etop]}};this._removeDupStyle=
function(a,b){if(a==null)return"";for(var c=null,c=a.style!=void 0&&typeof a.style.cssText=="string"?a.style.cssText.split(";"):a.getAttribute("style").split(";"),d="",e=c.length-1;e>=0;e--){var f=c[e].split(":");b.indexOf(f[0].replace(/^\s*/,"").replace(/\s*$/,"")+":")==-1&&(d+=c[e]+";")}return d.replace("; ",";").replace(/^ ;/,"").replace(/^\s*/,"").replace(/\s*$/,"")};this._setStyle=function(a,b){if(!(a==null||b==null)){var c=this._removeDupStyle(a,b),b=b.replace("; ",";");if(typeof a.style.cssText==
"string")a.style.cssText=c+b;a.setAttribute("style",c+b)}};this._getStyleProperty=function(a,b){if(a==null||b==null)return"";for(var c=null,c=typeof a.style.cssText=="string"?a.style.cssText.split(";"):a.getAttribute("style").split(";"),d=c.length-1;d>=0;d--){var e=c[d].split(":");if(b==e[0])return e[1].replace(/^\s+|\s+$/,"")}return""};this._keyboardNav=function(a){if(!this.IgnoreKeyboard&&(a=a?a:window.event?window.event:null))a=a.charChode?a.charCode:a.keyCode?a.keyCode:a.which?a.which:0,a>=49&&
a<=57&&this.ToggleTab(parseInt(String.fromCharCode(a))-1)};this._hideAll=function(){if(!(this.Tabs.length<=0)){for(var a=this.Tabs.length-1;a>=0;a--)this._setStyle(this.Tabs[a].name,"visibility: hidden;"),this._setStyle(this.Tabs[a].content,"visibility: hidden;"),this.Tabs[a].visible=!1;this._setStyle(this.Tabs[0].name.parentNode,"visibility: hidden;")}};this._showAll=function(){if(!(this.Tabs.length<=0)){this._setStyle(this.Tabs[0].name.parentNode,"visibility: visible;");for(var a=this.Tabs.length-
1;a>=0;a--)this._setStyle(this.Tabs[a].name,"visibility: visible;")}};this._hideTab=function(a,b){if(b<0||b>=a.length)return null;var c=a[b];if(c.visible){c.content.style.visibility="hidden";var d=c.name.getAttribute("class"),e=c.content.getAttribute("class");c.name.setAttribute("class",d.replace(" selected_tab",""));c.content.setAttribute("class",e.replace(" selected_content",""));c.visible=!1;c=this.NestedTabs[b];if(c!=null&&c.Tabs.length>0)this._setStyle(c.Tabs[0].parentNode,"visibility: hidden;"),
c._hideAll(),c.IgnoreKeyboard=!0}};this._showTab=function(a,b,c){if(b<0||b>=a.length)return null;a=a[b];if(!a.visible){this._showAll();var d=a.name.offsetWidth,e=a.name.offsetHeight,f=a.name.getAttribute("class"),g=a.content.getAttribute("class");this._setStyle(a.content,"visibility: visible;");a.name.setAttribute("class",f+" selected_tab");a.content.setAttribute("class",g+" selected_content");a.visible=!0;switch(c.Orientation){case LibTabs_Orientation.TOP:this._setStyle(a.name,"height: "+e+"px; width: "+
(d-13)+"px;");break;case LibTabs_Orientation.BOTTOM:this._setStyle(a.name,"width: "+(d-13)+"px;")}b=this.NestedTabs[b];if(b!=null&&b.Tabs.length>0)b._showAll(),b.CurrentTab==-1&&b.ToggleTab(0),this._setStyle(b.Tabs[b.CurrentTab].content,"visibility: visible;"),b.Tabs[b.CurrentTab].visible=!0,b.IgnoreKeyboard=!1}};this._addTopTab=function(a){a.setAttribute("class",a.getAttribute("class")+" top_tab");var b=null,c=null,a=a.childNodes,d=0,d=this.ExcludedTabs;for(child in a)if(a[child].nodeType!=void 0&&
a[child].nodeType!=Node.TEXT_NODE){var e=a[child].getAttribute("class");if(!(d!=null&&d.contains(a[child].firstChild.nodeValue)))e=="tab_name"&&b==null?(b=a[child],b.style.visibility="visible",b.setAttribute("onclick",this.ThisObj+".ToggleTab("+this.Tabs.length+");")):e.indexOf("tab_content")!=-1&&c==null&&(c=a[child])}if(b!=null&&c!=null){d=0;if(this.Tabs.length!=0)a=this.Tabs[this.Tabs.length-1].name,d=a.offsetWidth+parseInt(a.style.left)+this.TAB_NAME_SPACING;this._setStyle(b,"left: "+d+"px");
this._setStyle(c,"visibility: hidden");this.Tabs.push(new g(b,c,!1))}};this._addBottomTab=function(a){a.setAttribute("class",a.getAttribute("class")+" bottom_tab");var b=null,c=null,d=a.childNodes,e=0,e=this.ExcludedTabs;for(child in d)if(d[child].nodeType!=void 0&&d[child].nodeType!=Node.TEXT_NODE){var f=d[child].getAttribute("class");if(!(e!=null&&e.contains(d[child].firstChild.nodeValue)))f=="tab_name"&&b==null?(b=d[child],b.style.visibility="visible",b.setAttribute("onclick",this.ThisObj+".ToggleTab("+
this.Tabs.length+");")):f.indexOf("tab_content")!=-1&&c==null&&(c=d[child])}if(b!=null&&c!=null){a.innerHTML="";a.appendChild(c);a.appendChild(b);e=0;if(this.Tabs.length!=0)a=this.Tabs[this.Tabs.length-1].name,e=a.offsetWidth+parseInt(a.style.left)+this.TAB_NAME_SPACING;this._setStyle(b,"left: "+e+"px");this._setStyle(c,"visibility: hidden");this.Tabs.push(new g(b,c,!1))}};this._addLeftTab=function(a){a.setAttribute("class",a.getAttribute("class")+" left_tab");var b=null,c=null,a=a.childNodes;for(child in a)if(a[child].nodeType!=
void 0&&a[child].nodeType!=Node.TEXT_NODE){var d=a[child].getAttribute("class");d=="tab_name"&&b==null?(b=a[child],b.style.visibility="visible",b.setAttribute("onclick",this.ThisObj+".ToggleTab("+this.Tabs.length+");")):d.indexOf("tab_content")!=-1&&c==null&&(c=a[child])}if(b!=null&&c!=null){a=0;if(this.Tabs.length!=0)a=this.Tabs[this.Tabs.length-1].name,a=a.offsetHeight+parseInt(a.style.top)+(this.TAB_NAME_SPACING-2),this.Reloaded||(a+=8);this._setStyle(b,"top: "+a+"px");this._setStyle(c,"visibility: hidden");
this.Tabs.push(new g(b,c,!1))}};this._getNested=function(a){for(var b=a.getElementsByTagName("div"),c=null,a=0;a<b.length;a++)if(b[a].getAttribute("class")=="tab_content"){c=b[a];break}if(c==null)return null;b=c.getElementsByTagName("div");for(a=0;a<b.length;a++)if(b[a].getAttribute("class")=="tab_content")return b[a].parentNode.parentNode;return null};this.LoadTabs=function(a,b){if(a!=null){this.ParentLyr=a;this._gutterWidth=0;var c=a.getElementsByTagName("div");this.NestedTabs=[];for(var d=0;d<
c.length;d++)if(c[d].getAttribute("class")=="tab"){var e=this._getNested(c[d]);if(e!=null)e=new LibTabs(this.ThisObj+".NestedTabs["+this.Tabs.length+"]",e,0,this.Orientation+1),this.NestedTabs[this.Tabs.length]=e,e.HandleKeyboardInputs(),e.IgnoreKeyboard=!0,e.Tabs.length>0&&e._hideAll();switch(this.Orientation){case LibTabs_Orientation.RIGHT:case LibTabs_Orientation.LEFT:this._addLeftTab(c[d]);break;case LibTabs_Orientation.TOP:this._addTopTab(c[d]);break;case LibTabs_Orientation.BOTTOM:this._addBottomTab(c[d])}if(this.Orientation==
LibTabs_Orientation.LEFT||this.Orientation==LibTabs_Orientation.RIGHT)if(e=this.Tabs[this.Tabs.length-1].name.offsetWidth,e>this._gutterWidth)this._gutterWidth=e}if(this.Orientation==LibTabs_Orientation.LEFT||this.Orientation==LibTabs_Orientation.RIGHT){this._gutterWidth=70;for(d=this.Tabs.length-1;d>=0;d--)c=this.Tabs[d],this._setStyle(c.name,"width: "+(this._gutterWidth+6)+"px;"),this._setStyle(c.content,"left: "+(this._gutterWidth+18)+"px;")}(this.Orientation==LibTabs_Orientation.TOP||this.Orientation==
LibTabs_Orientation.BOTTOM)&&b!=void 0&&this.ToggleTab(b)}};this.ReloadTabs=function(){this.Tabs=[];this.Reloaded=!0;this.LoadTabs(this.ParentLyr,this.CurrentTab)};this.ToggleTab=function(a){if(a<0||a>=this.Tabs.length)return null;var b=this.CurrentTab,c=this.Tabs;this._hideTab(c,b);this._showTab(c,a,this);this.CurrentTab=a;this.Tabs[this.CurrentTab].content.focus();for(a=0;a<this.ToggleListeners.length;a++)this.ToggleListeners[a](b,this.CurrentTab)};this.AddToggleListener=function(a){a!=null&&this.ToggleListeners.push(a)};
this.NextTab=function(){this.ToggleTab((this.CurrentTab+1)%this.Tabs.length)};this.PrevTab=function(){this.ToggleTab((this.CurrentTab==0?this.Tabs.length:this.CurrentTab)-1)};this.Size=function(){return this.Tabs.length};this.HandleKeyboardInputs=function(){LibTabs_keyboardListeners.push(this.ThisObj);if(document.onkeydown==null)document.onkeydown=LibTabs_tabsNav,document.layers&&document.captureEvents(Event.KEYDOWN)};b!=null&&this.LoadTabs(b,c)};
