function HG_Feature(a,b,c,d){this.title=a;this.data=null;this.data_updated=!1;this.data_update_callback=b;this.data_retriever_callback=c;this.update_rate=d;this.created=!1}function HG_FeatureView(a,b){this.data=a;this.content_renderer=b;this.elem=null;this.HG_FEATURE_CLASS="hg_feature";this.HG_FEATURE_HEADER_CLASS="hg_feature_header";this.HG_FEATURE_CONTENT_CLASS="hg_feature_content"}
HG_FeatureView.prototype._createHeader=function(){var a=document.createElement("div");a.setAttribute("class",this.HG_FEATURE_HEADER_CLASS);a.appendChild(document.createTextNode(this.data.title));a.appendChild(document.createElement("hr"));this.elem.appendChild(a)};
HG_FeatureView.prototype.create=function(){this.elem=document.createElement("div");this.elem.setAttribute("class",this.HG_FEATURE_CLASS);this._createHeader();var a=document.createElement("div");a.setAttribute("id","feature_"+this.data.title.toLowerCase().replace(/\s/g,"_").replace(/,/g,""));a.setAttribute("class",this.HG_FEATURE_CONTENT_CLASS);this.elem.appendChild(a);this.created=!0};HG_FeatureView.prototype.render=function(){return this.content_renderer(this.elem.lastChild)};
HG_FeatureView.prototype.refresh=function(){this.elem.lastChild.innerHTML="";this.render()};function HG_FeatureManager(){this.elem=null;this.features=[];this.initial_create=!0;this.HG_FEATURES_CLASS="hg_features"}HG_FeatureManager.prototype._dataRetrieved=function(a){this.features[a].data.data_update_callback();this.renderFeature(a)};
HG_FeatureManager.prototype.renderFeature=function(a){var b=this.features[a];if(b.data.data_updated){if(!b.created){if(this.initial_create)this.elem.innerHTML="",this.initial_create=!1;b.create();this.elem.appendChild(b.elem)}b.render()}else b=b.data.data_retriever_callback,b!=null?HG_FeatureManager_dataLoadingTimer(b(),this,a):this._dataRetrieved(a)};HG_FeatureManager.prototype.addFeature=function(a){if(a==null)return!1;this.features.push(a);this.renderFeature(this.features.length-1);return!0};
HG_FeatureManager.prototype.create=function(a){this.elem=a;this.elem.setAttribute("class",this.HG_FEATURES_CLASS)};function HG_FeatureManager_dataLoadingTimer(a,b,c){eval(a)?b._dataRetrieved(c):setTimeout(function(){HG_FeatureManager_dataLoadingTimer(a,b,c,!1)},5E3)};var hg_domain_name="hokiegeek.net",hg_subdomains=[["books","My book library"],["albums","Pictures"],["house","House-related stuff"],["shaving","Shaving stuff"],["tea","My tea journal"]],hg_subdomains_public_lim=6,hg_subdomains_public_only=!0,domains_per_row=3,hg_nav__id="hg_nav",hg_nav__obj={logo:null,subdomains:null,timeout:null},hg_nav_main_id="hg_main_nav",hg_nav_subs_id="hg_subdomains",hg_nav__logo_over="hg_nav_logo_sel",hg_logo_class="hg_logo",hg_logo_small_class="hg_logo_small";
function hg_nav__onmouseover(){var a=hg_nav__obj.logo;if(a!=null){if(hg_nav__obj.timeout!=null)window.clearTimeout(hg_nav__obj.timeout),hg_nav__obj.timeout=null;var b=a.getAttribute("class");b.indexOf(hg_nav__logo_over)==-1&&a.setAttribute("class",b+" "+hg_nav__logo_over);setStyle(hg_nav__obj.subdomains,"position: relative; visibility: visible; left: 0px")}}
function hg_nav__onmouseout(){if(hg_nav__obj.logo!=null){var a=hg_nav__obj.logo.getAttribute("class").replace(" "+hg_nav__logo_over,"");hg_nav__obj.timeout=window.setTimeout('new function() { hg_nav__obj.logo.setAttribute("class", "'+a+'");setStyle(hg_nav__obj.subdomains, "position: absolute; visibility: hidden; left: -8000px"); }',400)}}
function hg_nav_main(a,b){var c=document.getElementById(a);if(c!=null){var d=document.createElement("div");d.setAttribute("id","hg_logo");d.setAttribute("class",hg_logo_class);d.appendChild(document.createTextNode(hg_domain_name.charAt(0).toUpperCase()+hg_domain_name.substring(1)));var e=document.createElement("div");e.setAttribute("id",hg_nav_subs_id);for(var f=document.createElement("div"),g=0;g<hg_subdomains.length;g++){if(hg_subdomains_public_only&&g==hg_subdomains_public_lim)break;var h=hg_subdomains[g],
i=document.createElement("a");i.setAttribute("href","http://"+h[0]+"."+hg_domain_name);i.setAttribute("target","_top");i.setAttribute("title",h[1]);b&&i.setAttribute("onmouseover",b+"("+g+")");var j=document.createElement("span");j.appendChild(document.createTextNode(h[0]));i.appendChild(j);f.appendChild(i);if(g%domains_per_row==domains_per_row-1||g==hg_subdomains.length-1)e.appendChild(f),f=document.createElement("div")}c.insertBefore(e,c.firstChild);c.insertBefore(d,c.firstChild)}}
function hg_small_nav(){var a=document.createElement("div");a.setAttribute("id",hg_nav__id);a.setAttribute("onmouseout","hg_nav__onmouseout()");a.setAttribute("onmouseover","hg_nav__onmouseover()");var b=document.createElement("div");b.setAttribute("id","hg_nav__subdomains");for(var c=0;c<hg_subdomains.length;c++){if(hg_subdomains_public_only&&c==hg_subdomains_public_lim)break;var d=hg_subdomains[c],e=document.createElement("a");e.setAttribute("href","http://"+d[0]+"."+hg_domain_name);e.setAttribute("target",
"_top");e.setAttribute("title",d[1]);e.appendChild(document.createTextNode(d[0]));c!=0&&b.appendChild(document.createTextNode("\u00a0\u00a0"));b.appendChild(e)}a.appendChild(b);c=document.createElement("a");c.appendChild(document.createTextNode(hg_domain_name));c.setAttribute("class",hg_logo_class+" "+hg_logo_small_class);c.setAttribute("href","http://"+hg_domain_name);c.setAttribute("target","_top");a.appendChild(c);hg_nav__obj.logo=c;hg_nav__obj.subdomains=b;b=9;for(d=1;d<6;d++){var e="opacity: ."+
b+";",f=document.createElement("div");f.setAttribute("class","hg_nav_fade");setStyle(f,e+" left: "+(d-1)+"px; border-right-width: 1px; ");a.insertBefore(f,c);f=document.createElement("div");f.setAttribute("class","hg_nav_fade");setStyle(f,e+" left: -"+d+"px; border-left-width: 1px; ");a.insertBefore(f,c);b-=2}document.body.appendChild(a)}var isIE=!1,url_match=/https?:\/\/([-\w\.]+)+(:\d+)?(\/([\w/_\.]*(\?\S+)?)?)?/;
function findMousePos(a){var b=0,c=0,a=a?a:window.event;if(isIE)b=event.clientX+document.body.scrollLeft,c=event.clientY+document.body.scrollTop;else if(a!=void 0)b=a.pageX,c=a.pageY;b<0&&(b=0);c<0&&(c=0);return[b,c]}function findPos(a){var b=etop=0;if(a.offsetParent){do b+=a.offsetLeft,etop+=a.offsetTop;while(a=a.offsetParent);return[b,etop]}}function findElemPos(a){return findPos(a)}function scrollToElem(a){a=findPos(a);window.scrollTo(a[0],a[1])}
function _removeDupStyle(a,b){for(var c=null,c=typeof a.style.cssText=="string"?a.style.cssText.split(";"):a.getAttribute("style").split(";"),d="",e=c.length-1;e>=0;e--){var f=c[e].split(":");b.indexOf(f[0]+":")==-1&&(d+=c[e]+";")}return d}function setStyle(a,b){if(!(a==null||b==null)){var c=_removeDupStyle(a,b);if(typeof a.style.cssText=="string")a.style.cssText=c+b;a.setAttribute("style",c+b)}}
function getStyleProperty(a,b){if(a==null||b==null)return"";for(var c=null,c=typeof a.style.cssText=="string"?a.style.cssText.split(";"):a.getAttribute("style").split(";"),d=c.length-1;d>=0;d--){var e=c[d].split(":");if(b==e[0])return e[1].replace(/^\s+|\s+$/,"")}return""}function addClass(a,b){if(a!=null){var c=a.getAttribute("class");c!=null&&c.length>0?c+=" ":c="";c+=b;a.setAttribute("class",c)}}
function removeClass(a,b){if(a!=null){var c=a.getAttribute("class");if(!(c==null||c.length<=0)){var d=eval("/\\s*"+b+"/"),c=c.replace(d,"");a.setAttribute("class",c)}}}var OKDListeners=null;function fireOnKeyDown(a){for(var b=0;b<OKDListeners.length;b++)OKDListeners[b](a)}function SetupOnKeyDown(){OKDListeners==null&&(OKDListeners=[]);document.onkeydown!=null&&OKDListeners.push(document.onkeydown);document.onkeydown=fireOnKeyDown;document.layers&&document.captureEvents(Event.KEYDOWN)}
function AddOKDListener(a){OKDListeners==null&&SetupOnKeyDown();OKDListeners.push(a);return OKDListeners.length-1}function RemoveOKDListener(a){a=OKDListeners.indexOf(a);if(!(a<0)){for(var b=[],c=OKDListeners.length-1;c>=0;c--)c!=a&&b.unshift(OKDListeners[c]);OKDListeners=b}}Array.prototype.contains=function(a){for(var b=this.length;b--;)if(this[b]!=null){var c=this[b];if(c.equals!=void 0&&c.equals(a))return!0;if(c===a)return!0}return!1};
Array.prototype.indexOf=function(a){for(var b=this.length;b--;){var c=this[b];if(c.equals!=void 0&&c.equals(a))return b;if(c===a)return b}return-1};Object.prototype.toString=function(){var a="{",b=!0;for(p in this){b?b=!1:a+=",";a+="'"+p+"': ";var c=this[p];if(c instanceof Array){a+="[";for(var d=0;d<c.length;d++)d!=0&&(a+=","),a+="'"+c[d]+"'";a+="]"}else a+="'"+c+"'"}a+="}";return a};
var weekdays_short=["Sun","Mon","Tue","Wed","Thu","Fri","Sat"],months_short=["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];function sameDay(a,b){return a.getFullYear()!=b.getFullYear()?!1:a.getMonth()!=b.getMonth()?!1:a.getDate()!=b.getDate()?!1:!0}function sameWeek(a,b){if(a.getFullYear()!=b.getFullYear())return!1;if(a.getMonth()!=b.getMonth())return!1;var c=a.getDate()-a.getDay(),d=c+6;return b.getDate()<c||b.getDate()>d?!1:!0}
function getVagueTime(a){var b=new Date,a=new Date(a),c="";b.getFullYear()!=a.getFullYear()?c=a.getMonth()+"/"+a.getDate()+"/"+a.getFullYear()+" ":sameDay(b,a)||(c=b.getDate()-1==a.getDate()?"Yesterday ":b.getDate()-a.getDate()<3?"A couple of days ago ":sameWeek(b,a)?weekdays_short[a.getDay()]+" ":months_short[a.getMonth()]+" "+a.getDate()+" ");sameDay(b,a)?(c=b.getHours()-a.getHours(),c=a.getHours()>b.getHours()?"From the mysterious future!":c<1?"A few minutes ago":c>=1&&c<2?"About an hour ago":
c>=2&&c<4?"A couple of hours ago":c>=4&&c<=6?"A few hours ago":a.getHours()<11?"This morning":a.getHours()>11&&a.getHours()<17?"This afternoon":"Earlier this evening"):b.getDate()-1==a.getDate()?c+=a.getHours()<11?"morning":a.getHours()>11&&a.getHours()<17?"afternoon":"evening":b.getDate()-a.getDate()>3&&(c+=a.getHours()%12+":"+a.getMinutes(),c+=a.getHours()>11?"pm":"am");return c}function getRandom(a){return Math.floor(Math.random()*a)}
function textToDOM(a){if(a==null)return null;if(a.indexOf(">")==-1&&a.indexOf("<")==-1)return document.createTextNode(a);for(var b=[];a.length>0;){var c=null;if(a.charAt(0)!="<")c=a.substring(0,a.indexOf("<")),a=a.substring(a.indexOf("<")),b.push(document.createTextNode(c));else{var c=a.substring(a.indexOf("<")+1,a.indexOf(">")),d=document.createElement(c),e=a.indexOf("/>"),f=a.indexOf("</"+c+">");if(e<0||e>=f){e=f;f=a.substring(a.indexOf(">")+1,e);if(f.indexOf("<")==-1)d.appendChild(document.createTextNode(f));
else for(var f=textToDOM(f),g=0,h=f.length;g<h;g++){var i=f[g];i!=null&&d.appendChild(i)}a=a.substring(c.length+e+3)}else a=a.substring(c.length+2);b.push(d)}}return b}function setTitle(a){var b=document.getElementsByTagName("title");b.length>0?b.innerHTML=a:(b=document.createElement("title"),b.appendChild(document.createTextNode(a)),document.head.appendChild(b))}
function getDocHeight(){return Math.max(Math.max(document.body.scrollHeight,document.documentElement.scrollHeight),Math.max(document.body.offsetHeight,document.documentElement.offsetHeight),Math.max(document.body.clientHeight,document.documentElement.clientHeight))}function HG_loadOnCondition(a,b,c){b!=null&&(eval(a)?b():setTimeout(function(){HG_loadOnCondition(a,b,c)},c))}var pw_albums=null,HG_Journal_tabsObj=null;
function HG_retrievePicturesFromAlbum(a,b){var c=a.split(";");c.pop();for(var d=c.length-1;d>=0;d--)c[d]=b!=null?b.getPicture(c[d]):null,c[d]==null&&(c[d]="img/default.png");return c}function HG_loadSpreadsheetEntries(a,b,c){if(a!=null&&a.length>0){b!=void 0&&b("Loading "+c.name+"...");for(a=a.length-1;a>=0;a--)eval(c.entries_var+".push(new "+c.entries_type+"(a["+a+"]))")}}
function HG_getSpreadsheetEntries(a,b,c,d){if(eval(a)){for(;b.length>0;)b.pop();getGoogleData(new GSpreadsheetRetrieval(c,d,null))}else setTimeout(function(){HG_getSpreadsheetEntries(a,b,c,d)},5E3)}
function HG_getJournalData(a,b){b!=void 0&&b("Loading pictures...");pw_albums==null&&(pw_albums=new PicasaWeb("andres.f.perez"));HG_loadOnCondition("pw_albums.isLoaded('"+a.album_id+"')",new Function("",a.album_var+" = pw_albums.getAlbum('"+a.album_id+"');"),1500);for(var c=[],d=0;d<a.spreadsheets.length;d++){var e=a.spreadsheets[d],f=null,f=e.retrieval_condition==void 0?c.length==0?"pw_albums.isLoaded('"+a.album_id+"')":"("+c[c.length-1]+".length > 0)":e.retrieval_condition==null?"true":e.retrieval_condition;
c.push(e.entries_var);try{HG_getSpreadsheetEntries(f,eval(e.entries_var),e.retrieval_url,new Function("entries","HG_loadSpreadsheetEntries(entries, "+b+", {'name':'"+e.name+"', 'entries_var':'"+e.entries_var+"', 'entries_type':'"+e.entries_type+"', });"))}catch(g){console.log("WTF? Something here just didn't work: ",g),console.trace()}}if(a.loaded_callback!=void 0&&a.loaded_callback!=null){if(a.loaded_condition==void 0){e="(";for(d=0;d<c.length;d++)d!=0&&(e+=" && "),e+=c[d]+".length > 0";e+=")"}else e=
a.loaded_condition;HG_loadOnCondition(e,a.loaded_callback,5E3)}return!0}function HG_formatDate(a,b){var c=b;b==void 0&&(c="%M/%D/%Y");var d=a.getMonth()+1;d.toString().length<2&&(d="0"+d);var e=a.getDate();e.toString().length<2&&(e="0"+e);var f=a.getFullYear();return c.replace("%Y",f).replace("%M",d).replace("%D",e)}function HG_getNextProductID(a){for(var b=-1,c=a.length-1;c>=0;c--)if(eval(a[c].ID)>b)b=a[c].ID;return++b}
function HG_getProductByID(a,b){if(a==null||b<0||b>=a.length)return console.log("  crap!: ",a==null,b<0,b>=a.length),null;for(var c=a.length-1;c>=0;c--)if(eval(a[c].ID)==b)return a[c];return null}function HG_Journal_loadingMessage(a){if(a!=null){var a=document.createTextNode(a),b=document.getElementById("hg_journal_loading");b!=null&&(b.removeChild(b.firstChild),b.insertBefore(a,b.firstChild))}}var filterBox=null,filterMsg=null,filter=null;
function HG_Journal_clearFilterValue(){filterMsg==null&&(filterMsg=document.getElementById("hg_journal_filter").getElementsByTagName("span")[0]);filterBox==null&&(filterBox=document.getElementById("hg_journal_filter_exp"));if(filter==null)filterBox.value=""}
function HG_Journal_resizeTabs(){for(var a=document.getElementsByTagName("div"),b=0;b<a.length;b++)if(a[b].getAttribute("class")=="tab_content"){var c=0,c=a[b].parentNode.parentNode.parentNode.getAttribute("class");c!=null&&c.indexOf("tab_content")!=-1?(c=a[b].parentNode.parentNode.parentNode.getAttribute("id")=="forms"?90:filteredTabsHeight,c=parseInt(document.documentElement.clientHeight-c)):c=parseInt(document.documentElement.clientHeight-60);setStyle(a[b],"height: "+c+"px !important;")}}
function HG_Journal_addControls(){var a=document.createElement("div");a.setAttribute("id","hg_journal_loading");a.appendChild(document.createTextNode("Loading..."));var b=document.createElement("img");b.setAttribute("src","../img/progress.gif");a.appendChild(b);document.body.insertBefore(a,document.body.firstChild);filter=document.createElement("div");filter.setAttribute("id","hg_journal_filter");filter.innerHTML='<span></span><input type="text" id="hg_journal_filter_exp" class="list_filter" value="" onfocus="filterFocusToggle(true);" onblur="filterFocusToggle(false);" />';
document.body.insertBefore(filter,document.body.firstChild);filterMsg==null&&(filterMsg=filter.getElementsByTagName("span")[0])}
function HG_Journal_keyboardHandler(a){if(a=a?a:window.event?window.event:null){var b=a.charChode?a.charCode:a.keyCode?a.keyCode:a.which?a.which:0;switch(b){case 191:case 27:case 13:case 222:if(getStyleProperty(filterBox,"visibility")=="hidden")break;filterBox==null&&(filterBox=document.getElementById("hg_journal_filter_exp"));if(filterBox!=null)if(filterBox.getAttribute("class"),filter_busy)b!=191&&filterFocusToggle(!1),b==13&&filterBox.value.length>0&&filterData(filterBox.value);else switch(b){case 191:filterFocusToggle(!0);
break;case 27:console.log("HERE: ",filterBox.value.length),filterBox.value.length>0&&filterData(null),setStyle(filterBox,"background-color: #fff")}a.cancelBubble=!0;a.returnValue=!1;a.stopPropagation&&(a.stopPropagation(),a.preventDefault());return!1}}}function HG_viewControls(){this.filter=this.sort_group=this.sort_dir=this.sort_field=null}function HG_Journals_View(a,b,c,d){this.data=a;this.sortable_fields=b;this.elem_id=c;this.renderer=d}
function HG_createJournalSorter(a,b){var c=document.getElementById("journal_sorter");c.innerHTML="";for(var d=0;d<b.sortable_fields.length;d++){var e=document.createElement("span");e.appendChild(document.createTextNode(b.sortable_fields[d]));var f=null,g=a.filter==null?"null":"'"+a.filter.replace(/'/g,"\\'")+"'",f="ASC";d==a.sort_field&&(f=document.createElement("img"),f.setAttribute("class","sort_arrow"),f.setAttribute("src","img/sort_"+(a.sort_dir=="ASC"?"up":"down")+".png"),e.appendChild(f),f=
a.sort_dir=="ASC"?"DESC":"ASC");e.setAttribute("title","Sort "+(f=="ASC"?"Ascending":"Descending"));var h="{",i=!0;for(p in b)if(i?i=!1:h+=",",h+="'"+p+"': ",b[p]instanceof Array){h+="[";for(var j=0;j<b[p].length;j++)j!=0&&(h+=","),h+="'"+b[p][j]+"'";h+="]"}else h+="'"+b[p]+"'";e.setAttribute("onclick","HG_renderJournal({'sort_field': "+d+", 'sort_dir': '"+f+"', 'sort_group': null, 'filter': "+g+"}, "+b.toString()+");");c.appendChild(e)}}
function HG_renderJournal(a,b){var c=eval(b.data),d=b.renderer;journalTable==null&&(journalTable=document.getElementById("journal"));var e=document.getElementById("journal_expand_collapse");if(e!=void 0)e.innerHTML=genExpandCollapseControls(!0,!1),delete e;HG_Journal_clearFilterValue();journalTable.innerHTML="";HG_createJournalSorter(a,b);var f=null,g=e=null,c=c.slice();a.sort_field==1&&c.sort(function(a,b){return grade_scale.indexOf(b.Grade)-grade_scale.indexOf(a.Grade)});var h=c.length-1;displayed_entries=
0;for(var i=h;i>-1;i--)if(f=a.sort_dir=="DESC"?i:h-i,a.filter==null||eval(a.filter))e=document.createElement("td"),e.innerHTML=HG_formatDate(c[f].Date),g=document.createElement("td"),displayed_entries%2||g.setAttribute("class","distinct_row"),eval(d+"(entry_elem, entries["+f+"], displayed_entries)")&&(displayed_entries++,f=document.createElement("tr"),f.setAttribute("onclick","toggleEntryDetails(this, true)"),f.appendChild(e),f.appendChild(g),journalTable.appendChild(f));displayed_entries<=3&&toggleJournalExpand(!0);
delete h;delete categories}
function HG_loadJournalViews(a,b){console.log("HG_loadJournalViews(",a,")");setStyle(document.getElementById("hg_journal_loading"),"visibility: hidden;");for(var c=0;c<a.length;c++)c==0?HG_renderJournal({sort_field:0,sort_dir:"DESC",sort_group:null,filter:null},a[c]):a[c].renderer();filterMsg.innerHTML="Showing "+displayed_entries+" entries";HG_Journal_resizeTabs();setStyle(filter,"visibility: visible;");HG_Journal_tabsObj=new LibTabs("HG_Journal_tabsObj",document.getElementById("hg_journal_tabs"),0,
LibTabs_Orientation.TOP,b);HG_Journal_tabsObj.HandleKeyboardInputs();AddOKDListener(HG_Journal_keyboardHandler)}function HG_Journal_init(){HG_Journal_addControls();filter=document.getElementById("hg_journal_filter_exp");window.location.hostname=="localhost"&&(hg_subdomains_public_only=!1);hg_small_nav();HG_Journal_local_init()}GSpreadsheetRetrieval.prototype=new GoogleDataRetrieval;
function GSpreadsheetRetrieval(a,b,c){this.URL=a;this.UserCallback=b;this.UserCallbackArguments=c;this.Service="wise";this.ArrayPos=-1;this.httpReq=new libHTTPRequest}GSpreadsheetRetrieval.prototype.retrieveEntries=function(a){for(var b=[],a=GoogleDataRetrieval.prototype.retrieveEntries(a),c=a.length-1;c>=0;c--)for(var d=a[c].length-1;d>=0;d--)if(a[c][d].content)content=a[c][d].content.$,content!=null&&b.push(this.createObjectFromEntry(content)),delete content;delete a;return b};
var GoogleDataRetrievals=[];function GoogleDataRetrieval(a,b,c,d){this.ArrayPos=-1;this.URL=a;this.Service=b;this.UserCallback=c;this.UserCallbackArguments=d;this.httpReq=new libHTTPRequest}GoogleDataRetrieval.prototype.createObjectFromEntry=function(a){var b=a,a=a.match(/,\s*[a-z_]*:\s/g);a.push(b.match(/^[a-z_]*:\s/)[0]);for(var c=null,d=a.length-1;d>=0;d--)c=a[d],b=b.replace(c,'"'+c.replace(/:\s/,'":').replace(/,\s/,', "')+'"'),delete c;delete a;return eval("[{"+b+'"}]')[0]};
GoogleDataRetrieval.prototype.retrieveEntries=function(a){var b=[];if(a.entry)b.push(a.entry["#"]);else if(a.feed){for(var a=a.feed["#"],c=null,d=a.length-1;d>=0;d--)a[d].entry&&(c=a[d].entry["#"],b.push(c));delete a}return b};
GoogleDataRetrieval.prototype.Callback=function(a){var b=null;try{a!="Token invalid"&&(a=a.replace(/\s/g," "),b=this.retrieveEntries(eval(a)[0]))}catch(c){console.log("  RET: ",a),console.log("GoogleDataRetrieval.Callback: err = "+c),console.trace(),b=null}finally{this.UserCallbackArguments!=null?this.UserCallback(b,this.UserCallbackArguments):this.UserCallback(b)}};
GoogleDataRetrieval.prototype.Retrieve=function(a){this.httpReq.getData(this.URL,"gs="+this.Service,function(b){var c=GoogleDataRetrievals[a];c!=null&&c!=void 0&&c.Callback(b)},!0)};function getGoogleData(a){a.ArrayPos=GoogleDataRetrievals.length;GoogleDataRetrievals.push(a);a.Retrieve(a.ArrayPos)}GSpreadsheetRetrieval.prototype=new GoogleDataRetrieval;
function GSpreadsheetRetrieval(a,b,c){this.URL=a;this.UserCallback=b;this.UserCallbackArguments=c;this.Service="wise";this.ArrayPos=-1;this.httpReq=new libHTTPRequest}GSpreadsheetRetrieval.prototype.retrieveEntries=function(a){for(var b=[],a=GoogleDataRetrieval.prototype.retrieveEntries(a),c=a.length-1;c>=0;c--)for(var d=a[c].length-1;d>=0;d--)if(a[c][d].content)content=a[c][d].content.$,content!=null&&b.push(this.createObjectFromEntry(content)),delete content;delete a;return b};
var LibSlideshow_Active=[];function LibSlideshow(a){this._ThumbnailsLayer=this._ImgLayer=this._MainLayer=null;this._isListening=!1;this._previousListener=null;this.Pictures=a;this.CurrentPicture=-1;a!=null&&this.LoadLarge()}LibSlideshow_KeyboardHandler=function(a){for(var a=a?a:window.event?window.event:null,b=LibSlideshow_Active.length-1;b>=0;b--){var c=LibSlideshow_Active[b];c._isListening&&c._fireKeyboardEvent(a)}};
LibSlideshow.prototype._fireKeyboardEvent=function(a){if(a)switch(a.charChode?a.charCode:a.keyCode?a.keyCode:a.which?a.which:0){case 72:this.Previous();break;case 76:this.Next();break;case 27:this.Exit()}};
LibSlideshow.prototype.ViewPicture=function(a){if(this._ImgLayer!=null){var b="";if(this._ThumbnailsLayer!=null){var c=this._ThumbnailsLayer.getElementsByTagName("img");if(this.CurrentPicture>=0){var d=c[this.CurrentPicture],b=d.getAttribute("class");b!=null&&b.length>0&&d.setAttribute("class",b.replace(/ current/,""))}}this._ImgLayer.setAttribute("src",this.Pictures[a]);this.CurrentPicture=a;this._ThumbnailsLayer!=null&&(a=c[this.CurrentPicture],b=a.getAttribute("class"),b==null&&(b=""),a.setAttribute("class",
b+" current"))}};LibSlideshow.prototype._slidePicture=function(a,b){if(a!=null){var c=(eval(a.CurrentPicture)+eval(b))%a.Pictures.length;c<0&&(c=a.Pictures.length-1);return a.ViewPicture(c)}};LibSlideshow.prototype.Next=function(a){if(!(a<0||a>LibSlideshow_Active.length))return a=LibSlideshow_Active[a],a==null||a.Pictures.length<=1?void 0:a._slidePicture(a,1)};
LibSlideshow.prototype.Previous=function(a){if(!(a<0||a>LibSlideshow_Active.length))return a=LibSlideshow_Active[a],a==null||a.Pictures.length<=1?void 0:a._slidePicture(a,-1)};LibSlideshow.prototype.Next=function(){return this._slidePicture(this,1)};LibSlideshow.prototype.Previous=function(){return this._slidePicture(this,-1)};
LibSlideshow.prototype.Exit=function(){if(this._previoustListener)document.onkeydown=this._previoustListener;this._MainLayer.parentNode.removeChild(this._MainLayer);for(var a=[],b=LibSlideshow_Active.length-1;b>=0;b--)LibSlideshow_Active[b]!=this&&a.unshift(LibSlideshow_Active[b]);LibSlideshow_Active=a};
LibSlideshow.prototype.LoadLarge=function(){LibSlideshow_Active.push(this);var a=LibSlideshow_Active.length-1,b=document.createElement("div");b.setAttribute("class","LibSlideshow");b.setAttribute("LibSlideshow_idx",a);var c=document.createElement("div");c.setAttribute("class","background");b.appendChild(c);var d=document.createElement("div"),c=document.createElement("img");d.appendChild(c);b.appendChild(d);d=null;if(this.Pictures.length>1){document.createElement("span").setAttribute("class","LibSlideshow_Close");
document.createElement("span").setAttribute("class","LibSlideshow_Previous");document.createElement("span").setAttribute("class","LibSlideshow_Next");for(var d=document.createElement("div"),e=this.Pictures.length-1;e>=0;e--){var f=document.createElement("img");f.setAttribute("src",this.Pictures[e]);f.setAttribute("onclick","LibSlideshow_Active["+a+"].ViewPicture("+e+");");d.insertBefore(f,d.firstChild)}b.appendChild(d)}document.body.appendChild(b);this._MainLayer=b;this._ImgLayer=c;this._ThumbnailsLayer=
d;if(document.onkeydown!=null)this._previoustListener=document.onkeydown;document.onkeydown=LibSlideshow_KeyboardHandler;this._isListening=!0;this.Next()};function PicasaWeb_Pic(a){this.data=a;this.caption=this.url=this.name=this.id=null;this.height=this.width=0;this.loaded=!1;this._load()}PicasaWeb_Pic.prototype.isLoaded=function(){return this.loaded};PicasaWeb_Pic.prototype.getURL=function(a){var b=this.url;a!=void 0&&a!=null&&(b+="/s"+a);b+="/"+this.name;return b};
PicasaWeb_Pic.prototype._load=function(){if(!(this.data==null&&this.data==void 0)){for(var a=this.data.length-1;a>=0;a--){var b=this.data[a];if(b!=null)if(b.title)this.name=b.title.$;else if(b.id){if(b=b.id.$,b!=null&&b!=void 0)this.id=b.slice(b.lastIndexOf("/")+1)}else if(b.content&&b.content!=null)b=b.content["@"].src,this.url=b.substr(0,b.lastIndexOf("/"))}this.loaded=!0}};
function PicasaWeb_Album(a,b){this.ALBUM_PICS_URL="https://picasaweb.google.com/data/feed/api/user/"+a+"/albumid";this.user=a;this.data=b;this.name=null;this.id=-1;this.Pics=this.updated=this.summary=this.url=null;this._load()}PicasaWeb_Album.prototype.isLoaded=function(){return this.isLoaded(null)};PicasaWeb_Album.prototype.isLoaded=function(a){if(this.Pics==null)return!1;for(var b=this.Pics.length-1;b>=0;b--)if(!(a!=void 0&&a!=null&&this.Pics[b].name!=a)&&!this.Pics[b].isLoaded())return!1;return!0};
PicasaWeb_Album.prototype.Size=function(){return this.Pics==null?0:this.Pics.length};PicasaWeb_Album.prototype.getPicture=function(a){for(var b=this.Pics.length-1;b>=0;b--)if(this.Pics[b].name==a)return this.Pics[b];return null};PicasaWeb_Album.prototype._retrievePics=function(a){if(this.Pics==null||this.Pics==void 0)this.Pics=[];if(a!=null&&a.length>0)for(var b=a.length-1;b>=0;b--)a[b]!=null&&this.Pics.push(new PicasaWeb_Pic(a[b]))};
PicasaWeb_Album.prototype._load=function(){for(var a=this.data.length-1;a>=0;a--){var b=this.data[a];if(b!=null)if(b.title)this.name=b.title.$;else if(b.id)b=b.id.$,this.id=b.slice(b.lastIndexOf("/")+1),this.url=this.ALBUM_PICS_URL+"/"+this.id;else if(b.summary)this.summary=b.summary.$}if(!(this.name!="HG_Shaving"&&this.name!="HG_Tea"&&this.name!="Our First House")&&this.id!=null){PicasaWebObjects_retrieving.push(this);var c=PicasaWebObjects_retrieving.length-1;getGoogleData(new PicasaWebRetrieval(this.url,
function(a){var b=PicasaWebObjects_retrieving[c];(b!=null||b!=void 0)&&b._retrievePics(a)},null))}};function PicasaWeb(a){this.USER_ALBUMS_URL="https://picasaweb.google.com/data/feed/api/user/"+a+"&access=private";this.user=a;this.Albums=this.cover=null;this._load()}PicasaWeb.prototype.isLoaded=function(){return this.isLoaded(null)};
PicasaWeb.prototype.isLoaded=function(a){if(this.Albums==null)return!1;for(var b=this.Albums.length-1;b>=0;b--)if(!(a!=void 0&&a!=null&&this.Albums[b].name!=a)&&!this.Albums[b].isLoaded())return!1;return!0};PicasaWeb.prototype.getAlbum=function(a){if(this.Albums!=null)for(var b=this.Albums.length-1;b>=0;b--)if(this.Albums[b].name==a)return this.Albums[b];return null};
PicasaWeb.prototype._retrieveAlbums=function(a){if(this.Albums==null||this.Albums==void 0)this.Albums=[];if(a!=null&&a.length>0)for(var b=a.length-1;b>=0;b--)(a[b]!=null||a[b]!=void 0)&&this.Albums.push(new PicasaWeb_Album(this.user,a[b]))};PicasaWeb.prototype._load=function(){PicasaWebObjects_retrieving.push(this);var a=PicasaWebObjects_retrieving.length-1;getGoogleData(new PicasaWebRetrieval(this.USER_ALBUMS_URL,function(b){PicasaWebObjects_retrieving[a]._retrieveAlbums(b)},null))};
var PicasaWebObjects_retrieverCount=-1,PicasaWebObjects_retrieving=[];PicasaWebRetrieval.prototype=new GoogleDataRetrieval;function PicasaWebRetrieval(a,b,c){this.URL=a;this.UserCallback=b;this.UserCallbackArguments=c;this.Service="lh2";this.ArrayPos=-1;this.httpReq=new libHTTPRequest}function PicasaWeb_PicView(a,b){this.pic=a;this.elem=b;this.PIC_CLASSNAME="PicasaWeb_PicView";this.PIC_SIZE=300;this._load()}
PicasaWeb_PicView.prototype._load=function(){if(this.elem!=null){this.elem.innerHTML="";addClass(this.elem,this.PIC_CLASSNAME);var a=document.createElement("img");a.setAttribute("src",this.pic.getURL(this.PIC_SIZE));this.elem.appendChild(a)}};
function PicasaWeb_AlbumView(a,b,c){this.album=a;this.elem=b;this.display_header=c;this.pics_view=this.header_view=null;this.ALBUM_CLASSNAME="PicasaWeb_AlbumView";this.ALBUM_HEADER_CLASSNAME="PicasaWeb_AlbumView_Header";this.ALBUM_PICS_CLASSNAME="PicasaWeb_AlbumView_Pics";this._load()}
PicasaWeb_AlbumView.prototype._load=function(){if(this.elem!=null){this.elem.innerHTML="";addClass(this.elem,this.ALBUM_CLASSNAME);if(this.display_header){this.header_view=document.createElement("div");addClass(this.header_view,this.ALBUM_HEADER_CLASSNAME);var a=document.createElement("span");a.appendChild(document.createTextNode(this.album.name));this.header_view.appendChild(a);this.elem.appendChild(this.header_view)}this.pics_view=document.createElement("div");addClass(this.pics_view,this.ALBUM_PICS_CLASSNAME);
for(a=this.album.Pics.length-1;a>=0;a--){var b=document.createElement("span");new PicasaWeb_PicView(this.album.Pics[a],b);this.pics_view.insertBefore(b,this.pics_view.firstChild)}this.elem.appendChild(this.pics_view)}};function PicasaWeb_View(a,b){this.albums=a;this.elem=b;this.album_views=null;this.ALBUMS_CLASSNAME="PicasaWeb_View"}PicasaWeb_View.prototype._load=function(){this.elem.innerHTML="";addClass(this.elem,this.ALBUMS_CLASSNAME)};var PicasaWeb_PicSelectObjs=[];
function PicasaWeb_PicSelect(a,b,c,d){console.log("PicasaWeb_PicSelect()");a=new PicasaWeb_PicSelect_View(a,b,c);if(a==null)return[];console.log("   creating selection control");a.pos=PicasaWeb_PicSelectObjs.length;PicasaWeb_PicSelectObjs.push(a);a.show_header=!1;a.multiselect=d;a.load();return a}
function PicasaWeb_PicSelect_View(a,b,c){this.album=a;this.elem=b;this.pos=-1;this.thumb_size=50;this.multiselect=this.show_header=!0;this.callback=c;this.Selected=[];this.PICSELECT_CLASSNAME="PicasaWeb_PicSelect";this.PICSELECT_PICS_CLASSNAME="PicasaWeb_PicSelect_Pics";this.PICSELECT_PIC_CLASSNAME="PicasaWeb_PicSelect_Pic";this.PICSELECT_SELECTED_CLASSNAME="PicasaWeb_PicSelect_Pic_Selected";this.PICSELECT_HDR_CLASSNAME="PicasaWeb_PicSelect_Header";this.PICSELECT_BTN_CLASSNAME="PicasaWeb_PicSelect_Button"}
PicasaWeb_PicSelect_View.prototype.select=function(a,b){this.Selected.contains(a)?(this.Selected.splice(this.Selected.indexOf(a),1),removeClass(b,this.PICSELECT_SELECTED_CLASSNAME)):(this.Selected.push(a),addClass(b,this.PICSELECT_SELECTED_CLASSNAME),this.multiselect||this.close())};PicasaWeb_PicSelect_View.prototype.getSelected=function(){for(var a=[],b=0;b<this.Selected.length;b++)a.push(this.album.Pics[this.Selected[b]]);return a};
PicasaWeb_PicSelect_View.prototype.close=function(){if(this.elem!=null)this.elem.innerHTML="";this.callback!=null&&this.callback(this.getSelected())};
PicasaWeb_PicSelect_View.prototype.load=function(){if(this.album==null||this.elem==null)console.log("WTF?",this.album,this.elem);else{var a=document.createElement("div");addClass(a,this.PICSELECT_CLASSNAME);if(this.show_header){var b=document.createElement("div");addClass(b,this.PICSELECT_HDR_CLASSNAME);if(this.multiselect){var c=document.createElement("div");addClass(c,this.PICSELECT_BTN_CLASSNAME);c.setAttribute("onclick","PicasaWeb_PicSelectObjs["+this.pos+"].close()");c.appendChild(document.createTextNode("Done"));
b.appendChild(c)}c=document.createElement("div");c.appendChild(document.createTextNode(this.album.name+" ("+this.album.Pics.length+")"));b.appendChild(c);a.appendChild(b)}b=document.createElement("div");addClass(b,this.PICSELECT_PICS_CLASSNAME);for(var c=this.album.Pics,d=0;d<c.length;d++){var e=document.createElement("img");e.setAttribute("src",c[d].getURL(this.thumb_size));e.setAttribute("onclick","PicasaWeb_PicSelectObjs["+this.pos+"].select("+d+", this)");addClass(e,this.PICSELECT_PIC_CLASSNAME);
b.appendChild(e)}a.appendChild(b);this.elem.appendChild(a)}};var libHTTPRequest_Constants={MSXML_VERS:["MSXML2.XMLHttp.6.0","MSXML2.XMLHttp.5.0","MSXML2.XMLHttp.4.0","MSXML2.XMLHttp.3.0","MSXML2.XMLHttp","Microsoft.XMLHttp"],useActiveX:typeof ActiveXObject!="undefined",useDom:document.implementation&&document.implementation.createDocument,useXmlHttp:typeof XMLHttpRequest!="undefined"},libHTTPRequest_Requests=[];
function libHTTPRequest_DataManager(){this.Scripts=["http://"+window.location.hostname+"/sss/XDRequest.php"];this.StoreLocation="http://"+window.location.hostname+"/sss/gen"}
function libHTTPRequest(){this.Request=this.Callback=this.Options=this.URL=null;this.Store=!1;this.StoreFileName="libHTTPRequest";this.DataManager=new libHTTPRequest_DataManager;this.DataScript=null;this._XmlHttpReq=function(){if(typeof XMLHttpRequest!="undefined")return new XMLHttpRequest;else if(libHTTPRequest_Constants.useActiveX)for(var a=0;a<libHTTPRequest_Constants.MSXML_VERS.length;a++)try{return new ActiveXObject(libHTTPRequest_Constants.MSXML_VERS[a])}catch(b){}throw Error("XMLHttp object could not be created.");
};this.ping=function(a){var b=this._XmlHttpReq(),c=!1;b.open("GET",a,!1);try{b.send(null),b!=null&&b.readyState=="4"&&b.status>=200&&b.status<=207&&(c=!0)}catch(d){}return c};this._load=function(){for(var a=new libHTTPRequest_DataManager,b=0;b<a.Scripts.length;b++)if(this.ping(a.Scripts[b])){this.DataScript=a.Scripts[b];break}};this._load()}
libHTTPRequest._onreadystatechange=function(a){var b=libHTTPRequest_Requests[a],c=b.Request,d=b.Callback,b=b.Store;if(c!=null&&c.readyState=="4")switch(c.status){case 200:case 201:case 202:case 203:case 204:case 205:case 206:case 207:var e=null,e=c.responseXML&&c.responseXML.length>0?c.responseXML:c.responseText;e!=null&&d!=null?d(e):b&&libHTTPRequest._loadFromBackup(a);break;default:b&&libHTTPRequest._loadFromBackup(a)}};
libHTTPRequest._loadFromBackup=function(a){var b=libHTTPRequest_Requests[a],c=new libHTTPRequest_DataManager;this.StoreLocation="http://dl.dropbox.com/u/6524/hokiegeek.net/sss/gen";a=b.getXmlRequest("GET",c.StoreLocation+"/"+b.StoreFileName+".json",a);b.Request=a;a.send(null)};libHTTPRequest.prototype.getXmlRequest=function(a,b,c){var d=this._XmlHttpReq();d.onreadystatechange=function(){libHTTPRequest._onreadystatechange(c)};d.open(a,b,!0);return d};
libHTTPRequest.prototype.getData=function(a,b,c,d){if(a!=void 0){this.URL=a;this.Options=b;this.Callback=c;if(this.Store=d)c=a,a.indexOf("?")!=-1&&(c=a.substring(0,a.indexOf("?"))),c=c.replace(/https?:\/\//g,"").replace(/(\/|\.|\-|=|&)/g,"_"),this.StoreFileName+="__"+c,b+="&store="+this.StoreFileName;libHTTPRequest_Requests.push(this);this.Request=a=this.getXmlRequest("GET",this.DataScript+"?u="+a+"&"+b,libHTTPRequest_Requests.length-1);a.send(null)}};
libHTTPRequest.prototype.sendData=function(a,b){this.URL=a;this.Options=b;for(var c="",d=0;d<b.length;d++)d>0&&(c+="&"),c+=b[d];libHTTPRequest_Requests.push(this);d=this.getXmlRequest("POST",this.DataScript+"?u="+a,libHTTPRequest_Requests.length-1);d.setRequestHeader("Content-type","application/x-www-form-urlencoded");this.Request=d;d.send(c)};var LibTabs_Orientation={TOP:0,LEFT:1,BOTTOM:2,RIGHT:3},LibTabs_keyboardListeners=[];
function LibTabs_tabsNav(a){for(var b=LibTabs_keyboardListeners.length-1;b>=0;b--)eval(LibTabs_keyboardListeners[b])._keyboardNav(a)}
function LibTabs(a,b,c,d,e){function f(a,b){this.name=a;this.content=b;this.visible=!1}this.ThisObj=a;this.ParentLyr=null;this.CurrentTab=-1;this.Tabs=[];this.Orientation=d==void 0?LibTabs_Orientation.TOP:d;this.NestedTabs=[];this._gutterWidth=0;this.IgnoreKeyboard=!1;this.ToggleListeners=[];this.ExcludedTabs=e;this.Reloaded=!1;this.TAB_NAME_SPACING=5;this._findPos=function(a){var b=etop=0;if(a.offsetParent){do b+=a.offsetLeft,etop+=a.offsetTop;while(a=a.offsetParent);return[b,etop]}};this._removeDupStyle=
function(a,b){if(a==null)return"";for(var c=null,c=a.style!=void 0&&typeof a.style.cssText=="string"?a.style.cssText.split(";"):a.getAttribute("style").split(";"),d="",e=c.length-1;e>=0;e--){var f=c[e].split(":");b.indexOf(f[0].replace(/^\s*/,"").replace(/\s*$/,"")+":")==-1&&(d+=c[e]+";")}return d.replace("; ",";").replace(/^ ;/,"").replace(/^\s*/,"").replace(/\s*$/,"")};this._setStyle=function(a,b){if(!(a==null||b==null)){var c=this._removeDupStyle(a,b),b=b.replace("; ",";");if(typeof a.style.cssText==
"string")a.style.cssText=c+b;a.setAttribute("style",c+b)}};this._getStyleProperty=function(a,b){if(a==null||b==null)return"";for(var c=null,c=typeof a.style.cssText=="string"?a.style.cssText.split(";"):a.getAttribute("style").split(";"),d=c.length-1;d>=0;d--){var e=c[d].split(":");if(b==e[0])return e[1].replace(/^\s+|\s+$/,"")}return""};this._keyboardNav=function(a){if(!this.IgnoreKeyboard&&(a=a?a:window.event?window.event:null))a=a.charChode?a.charCode:a.keyCode?a.keyCode:a.which?a.which:0,a>=49&&
a<=57&&this.ToggleTab(parseInt(String.fromCharCode(a))-1)};this._hideAll=function(){if(!(this.Tabs.length<=0)){for(var a=this.Tabs.length-1;a>=0;a--)this._setStyle(this.Tabs[a].name,"visibility: hidden;"),this._setStyle(this.Tabs[a].content,"visibility: hidden;"),this.Tabs[a].visible=!1;this._setStyle(this.Tabs[0].name.parentNode,"visibility: hidden;")}};this._showAll=function(){if(!(this.Tabs.length<=0)){this._setStyle(this.Tabs[0].name.parentNode,"visibility: visible;");for(var a=this.Tabs.length-
1;a>=0;a--)this._setStyle(this.Tabs[a].name,"visibility: visible;")}};this._hideTab=function(a,b){if(b<0||b>=a.length)return null;var c=a[b];if(c.visible){c.content.style.visibility="hidden";var d=c.name.getAttribute("class"),e=c.content.getAttribute("class");c.name.setAttribute("class",d.replace(" selected_tab",""));c.content.setAttribute("class",e.replace(" selected_content",""));c.visible=!1;c=this.NestedTabs[b];if(c!=null&&c.Tabs.length>0)this._setStyle(c.Tabs[0].parentNode,"visibility: hidden;"),
c._hideAll(),c.IgnoreKeyboard=!0}};this._showTab=function(a,b,c){if(b<0||b>=a.length)return null;a=a[b];if(!a.visible){this._showAll();var d=a.name.offsetWidth,e=a.name.offsetHeight,f=a.name.getAttribute("class"),l=a.content.getAttribute("class");this._setStyle(a.content,"visibility: visible;");a.name.setAttribute("class",f+" selected_tab");a.content.setAttribute("class",l+" selected_content");a.visible=!0;switch(c.Orientation){case LibTabs_Orientation.TOP:this._setStyle(a.name,"height: "+e+"px; width: "+
(d-13)+"px;");break;case LibTabs_Orientation.BOTTOM:this._setStyle(a.name,"width: "+(d-13)+"px;")}b=this.NestedTabs[b];if(b!=null&&b.Tabs.length>0)b._showAll(),b.CurrentTab==-1&&b.ToggleTab(0),this._setStyle(b.Tabs[b.CurrentTab].content,"visibility: visible;"),b.Tabs[b.CurrentTab].visible=!0,b.IgnoreKeyboard=!1}};this._addTopTab=function(a){a.setAttribute("class",a.getAttribute("class")+" top_tab");var b=null,c=null,a=a.childNodes,d=0,d=this.ExcludedTabs;for(child in a)if(a[child].nodeType!=void 0&&
a[child].nodeType!=Node.TEXT_NODE){var e=a[child].getAttribute("class");if(!(d!=null&&d.contains(a[child].firstChild.nodeValue)))e=="tab_name"&&b==null?(b=a[child],b.style.visibility="visible",b.setAttribute("onclick",this.ThisObj+".ToggleTab("+this.Tabs.length+");")):e.indexOf("tab_content")!=-1&&c==null&&(c=a[child])}if(b!=null&&c!=null){d=0;if(this.Tabs.length!=0)a=this.Tabs[this.Tabs.length-1].name,d=a.offsetWidth+parseInt(a.style.left)+this.TAB_NAME_SPACING;this._setStyle(b,"left: "+d+"px");
this._setStyle(c,"visibility: hidden");this.Tabs.push(new f(b,c,!1))}};this._addBottomTab=function(a){a.setAttribute("class",a.getAttribute("class")+" bottom_tab");var b=null,c=null,d=a.childNodes,e=0,e=this.ExcludedTabs;for(child in d)if(d[child].nodeType!=void 0&&d[child].nodeType!=Node.TEXT_NODE){var k=d[child].getAttribute("class");if(!(e!=null&&e.contains(d[child].firstChild.nodeValue)))k=="tab_name"&&b==null?(b=d[child],b.style.visibility="visible",b.setAttribute("onclick",this.ThisObj+".ToggleTab("+
this.Tabs.length+");")):k.indexOf("tab_content")!=-1&&c==null&&(c=d[child])}if(b!=null&&c!=null){a.innerHTML="";a.appendChild(c);a.appendChild(b);e=0;if(this.Tabs.length!=0)a=this.Tabs[this.Tabs.length-1].name,e=a.offsetWidth+parseInt(a.style.left)+this.TAB_NAME_SPACING;this._setStyle(b,"left: "+e+"px");this._setStyle(c,"visibility: hidden");this.Tabs.push(new f(b,c,!1))}};this._addLeftTab=function(a){a.setAttribute("class",a.getAttribute("class")+" left_tab");var b=null,c=null,a=a.childNodes;for(child in a)if(a[child].nodeType!=
void 0&&a[child].nodeType!=Node.TEXT_NODE){var d=a[child].getAttribute("class");d=="tab_name"&&b==null?(b=a[child],b.style.visibility="visible",b.setAttribute("onclick",this.ThisObj+".ToggleTab("+this.Tabs.length+");")):d.indexOf("tab_content")!=-1&&c==null&&(c=a[child])}if(b!=null&&c!=null){a=0;if(this.Tabs.length!=0)a=this.Tabs[this.Tabs.length-1].name,a=a.offsetHeight+parseInt(a.style.top)+(this.TAB_NAME_SPACING-2),this.Reloaded||(a+=8);this._setStyle(b,"top: "+a+"px");this._setStyle(c,"visibility: hidden");
this.Tabs.push(new f(b,c,!1))}};this._getNested=function(a){for(var b=a.getElementsByTagName("div"),c=null,a=0;a<b.length;a++)if(b[a].getAttribute("class")=="tab_content"){c=b[a];break}if(c==null)return null;b=c.getElementsByTagName("div");for(a=0;a<b.length;a++)if(b[a].getAttribute("class")=="tab_content")return b[a].parentNode.parentNode;return null};this.LoadTabs=function(a,b){if(a!=null){this.ParentLyr=a;this._gutterWidth=0;var c=a.getElementsByTagName("div");this.NestedTabs=[];for(var d=0;d<
c.length;d++)if(c[d].getAttribute("class")=="tab"){var e=this._getNested(c[d]);if(e!=null)e=new LibTabs(this.ThisObj+".NestedTabs["+this.Tabs.length+"]",e,0,this.Orientation+1),this.NestedTabs[this.Tabs.length]=e,e.HandleKeyboardInputs(),e.IgnoreKeyboard=!0,e.Tabs.length>0&&e._hideAll();switch(this.Orientation){case LibTabs_Orientation.RIGHT:case LibTabs_Orientation.LEFT:this._addLeftTab(c[d]);break;case LibTabs_Orientation.TOP:this._addTopTab(c[d]);break;case LibTabs_Orientation.BOTTOM:this._addBottomTab(c[d])}if(this.Orientation==
LibTabs_Orientation.LEFT||this.Orientation==LibTabs_Orientation.RIGHT)if(e=this.Tabs[this.Tabs.length-1].name.offsetWidth,e>this._gutterWidth)this._gutterWidth=e}if(this.Orientation==LibTabs_Orientation.LEFT||this.Orientation==LibTabs_Orientation.RIGHT){this._gutterWidth=70;for(d=this.Tabs.length-1;d>=0;d--)c=this.Tabs[d],this._setStyle(c.name,"width: "+(this._gutterWidth+6)+"px;"),this._setStyle(c.content,"left: "+(this._gutterWidth+18)+"px;")}(this.Orientation==LibTabs_Orientation.TOP||this.Orientation==
LibTabs_Orientation.BOTTOM)&&b!=void 0&&this.ToggleTab(b)}};this.ReloadTabs=function(){this.Tabs=[];this.Reloaded=!0;this.LoadTabs(this.ParentLyr,this.CurrentTab)};this.ToggleTab=function(a){if(a<0||a>=this.Tabs.length)return null;var b=this.CurrentTab,c=this.Tabs;this._hideTab(c,b);this._showTab(c,a,this);this.CurrentTab=a;this.Tabs[this.CurrentTab].content.focus();for(a=0;a<this.ToggleListeners.length;a++)this.ToggleListeners[a](b,this.CurrentTab)};this.AddToggleListener=function(a){a!=null&&this.ToggleListeners.push(a)};
this.NextTab=function(){this.ToggleTab((this.CurrentTab+1)%this.Tabs.length)};this.PrevTab=function(){this.ToggleTab((this.CurrentTab==0?this.Tabs.length:this.CurrentTab)-1)};this.Size=function(){return this.Tabs.length};this.HandleKeyboardInputs=function(){LibTabs_keyboardListeners.push(this.ThisObj);if(document.onkeydown==null)document.onkeydown=LibTabs_tabsNav,document.layers&&document.captureEvents(Event.KEYDOWN)};b!=null&&this.LoadTabs(b,c)};
